USE perpetuumsa
GO

SET IDENTITY_INSERT [dbo].[teleportdescriptions] ON 

INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (578, N'Teleport_column_tm_cadavria_to_TP_zone_8_10', 5329, 248, 0, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'Teleport_Column_tm_Cadavria', N'tp_zone_8_10')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (579, N'TP_zone_8_10_to_Teleport_Column_tm_cadavria', 248, 5329, 8, 7, 0, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'tp_zone_8_10', N'teleport_column_TM_cadavria')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (580, N'Teleport_Column_TM_bellicha_z_to_tp_zone_8_10', 11641, 248, 0, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'Teleport_column_TM_Bellicha_Z', N'TP_Zone_8_10')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (581, N'tp_zone_8_10_to_Teleport_column_TM_Bellicha_z', 248, 11641, 8, 7, 0, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'TP_Zone_8_10', N'Teleport_column_TM_Bellicha_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (582, N'teleport_column_tmpve_1_to_teleport_column_ICS2_hillmanoc_Z', 108, 1315, 8, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'Teleport_Column_tmpve_1', N'teleport_column_ics2_hillmanoc_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (583, N'teleport_column_ICS2_hillmanoc_Z_to_teleport_column_tmpve_1', 1315, 108, 3, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_ics2_hillmanoc_z', N'Teleport_Column_tmpve_1')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (584, N'teleport_column_tmpve_1_to_teleport_column_moyar', 108, 92, 8, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'Teleport_column_tmpve_1', N'teleport_column_moyar')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (585, N'teleport_column_moyar_to_teleport_column_tmpve_1', 92, 108, 3, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_moyar', N'Teleport_column_tmpve_1')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (586, N'teleport_column_tmpve_1_to_teleport_column_ics2_panagox', 108, 1312, 8, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpve_1', N'Teleport_column_ics2_panagox')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (587, N'teleport_column_ics2_panagox_to_teleport_column_tmPVE_1', 1312, 108, 3, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'Teleport_column_ics2_panagox', N'teleport_column_tmpve_1')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (588, N'teleport_column_tmpve_5_to_teleport_column_tm2_haddonwol_Z', 112, 11640, 8, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpve_5', N'teleport_column_tm2_haddonwol_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (589, N'teleport_column_tm2_haddonwol_2_to_teleport_column_tmpve_5', 11640, 112, 5, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tm2_haddonwol_z', N'teleport_column_tmpve_5')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (590, N'teleport_column_tmpve_5_to_teleport_column_tm2_Karapyth_Z', 112, 11642, 8, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'Teleport_Column_tmpve_5', N'teleport_column_tm2_karapyth_z')
GO
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (591, N'teleport_column_tm2_karapyth_z_to_teleport_column_tmpve_5', 11642, 112, 5, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tm2_karapyth_z', N'Teleport_Column_tmpve_5')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (592, N'teleport_column_tmpve_5_to_tp_zone_5_9', 112, 1896, 8, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpve_5', N'tp_zone_5_9')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (593, N'tp_zone_5_9_to_teleport_column_tmpve_5', 1896, 112, 5, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'tp_zone_5_9', N'teleport_column_tmpve_5')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (594, N'teleport_column_initia_SW_to_TP_Zone_5_13', 95, 1423, 5, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_initia_SW', N'TP_zone_5_13')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (595, N'TP_zone_5_13_to_teleport_column_initia_SW', 1423, 95, 5, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'TP_zone_5_13', N'teleport_column_initia_SW')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (596, N'teleport_column_tm2_karapyth_z_to_teleport_column_tmpvp_5', 11642, 126, 5, 7, 10, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tm2_karapyth_z', N'teleport_column_tmpvp_5')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (597, N'teleport_column_tmpvp_5_to_teleport_column_tm2_karapyth_z', 126, 11642, 10, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpvp_5', N'teleport_column_tm2_karapyth_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (598, N'teleport_column_tm2_uiria_z_to_teleport_column_tmpvp_7', 41552, 128, 5, 7, 10, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tm2_uiria_z', N'teleport_column_tmpvp_7')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (599, N'teleport_column_tmpvp_7_to_teleport_column_tm2_uiria_z', 128, 41552, 10, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpvp_7', N'teleport_column_tm2_uiria_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (600, N'teleport_column_tmpvp_1_to_teleport_column_moyar', 122, 92, 10, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpvp_1', N'teleport_column_moyar')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (601, N'teleport_column_ics2_vsehovski_Z_to_teleport_column_tmpvp_2', 1316, 124, 3, 7, 10, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_ics2_vsehovski_z', N'teleport_column_tmpvp_2')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (602, N'teleport_column_moyar_to_teleport_column_tmpvp_1', 92, 122, 3, 7, 10, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_moyar', N'teleport_column_tmpvp_1')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (603, N'teleport_column_tmpvp_2_to_teleport_column_ICS2_vsehovski_z', 124, 1316, 10, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpvp_2', N'teleport_column_ICS2_vsehovski_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (604, N'teleport_column_TMPVE_6_to_teleport_column_asi2_nauwy_z', 113, 317, 8, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_TMPVE_6', N'teleport_column_asi2_nauwy_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (605, N'teleport_column_asi2_nauwy_z_to_teleport_column_TMPVE_6', 317, 113, 4, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asi2_nauwy_z', N'teleport_column_TMPVE_6')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (606, N'teleport_column_tmpve_6_to_teleport_column_teodoma', 113, 90, 8, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpve_6', N'teleport_column_teodoma')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (607, N'teleport_column_teodoma_to_teleport_column_tmpve_6', 90, 113, 4, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_teodoma', N'teleport_column_tmpve_6')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (608, N'teleport_column_asi2_gavastrac_to_teleport_column_tmpve_6', 312, 113, 4, 7, 8, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asi2_gavastrac', N'teleport_column_tmpve_6')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (609, N'tp_zone_4_13_to_teleport_column_vougar_nw', 1430, 91, 4, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'tp_zone_4_13', N'teleport_column_vougar_nw')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (610, N'teleport_column_vougar_nw_to_tp_zone_4_13', 91, 1430, 4, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_vougar_nw', N'tp_zone_4_13')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (611, N'teleport_column_teodoma_to_teleport_column_asipvp_1', 90, 114, 4, 7, 9, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_teodoma', N'teleport_column_asipvp_1')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (612, N'teleport_column_asipvp_1_to_teleport_column_teodoma', 114, 90, 9, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asipvp_1', N'teleport_column_teodoma')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (613, N'teleport_column_asi2_darmahol_to_teleport_column_asipvp_7', 313, 120, 4, 7, 9, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asi2_darmahol', N'teleport_column_asipvp_7')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (614, N'teleport_column_asipvp_7_to_teleport_column_asi2_darmahol', 120, 313, 9, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asipvp_7', N'teleport_column_asi2_darmahol')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (615, N'teleport_column_tm2_haddonwol_z_to_teleport_column_asipvp_4', 11640, 117, 5, 7, 9, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tm2_haddonwol_z', N'teleport_column_asipvp_4')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (616, N'teleport_column_asipvp_4_to_teleport_column_tm2_haddonwol_z', 117, 11640, 9, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asipvp_4', N'teleport_column_tm2_haddonwol_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (617, N'tp_zone_5_9_to_teleport_column_asipvp_8', 1896, 121, 5, 7, 9, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'tp_zone_5_9', N'teleport_column_asipvp_8')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (618, N'teleport_column_asipvp_8_to_tp_zone_5_9', 121, 1896, 9, 7, 5, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asipvp_8', N'tp_zone_5_9')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (619, N'teleport_column_asi2_gavastrac_to_teleport_column_icspvp_6', 312, 137, 4, 7, 11, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_asi2_gavastrac', N'teleport_column_icspvp_6')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (620, N'teleport_column_icspvp_6_to_teleport_column_asi2_gavastrac', 137, 312, 11, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_icspvp_6', N'teleport_column_asi2_gavastrac')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (621, N'teleport_column_icspvp_3_to_teleport_column_vougar_NW', 131, 91, 11, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_icspvp_3', N'teleport_column_vougar_NW')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (622, N'teleport_column_vougar_NW_to_teleport_column_icspvp_3', 91, 131, 4, 7, 11, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_vougar_NW', N'teleport_column_icspvp_3')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (623, N'teleport_column_ics2_koykili_z_to_teleport_column_icspvp_1', 1314, 129, 3, 7, 11, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_ics2_koykili_z', N'teleport_column_icspvp_1')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (624, N'teleport_column_icspvp_1_to_teleport_column_ics2_koykili_z', 129, 1314, 11, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_icspvp_1', N'teleport_column_ics2_koykili_z')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (625, N'teleport_column_tmpve_6_to_teleport_column_asi2_gavastrac', 113, 312, 8, 7, 4, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_tmpve_6', N'teleport_column_asi2_gavastrac')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (626, N'teleport_column_icspvp_7_to_teleport_column_ics2_panagox', 138, 1312, 11, 7, 3, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_icspvp_7', N'teleport_column_ics2_panagox')
INSERT [dbo].[teleportdescriptions] ([id], [description], [sourcecolumn], [targetcolumn], [sourcezone], [sourcerange], [targetzone], [targetx], [targety], [targetz], [targetrange], [usetimeout], [listable], [active], [type], [sourcecolumnname], [targetcolumnname]) VALUES (627, N'teleport_column_ics2_panagox_to_teleport_column_icspvp_7', 1312, 138, 3, 7, 11, NULL, NULL, NULL, 7, 0, 1, 1, 2, N'teleport_column_ics2_panagox', N'teleport_column_icspvp_7')

SET IDENTITY_INSERT [dbo].[teleportdescriptions] OFF



UPDATE teleportdescriptions
SET
	listable = 0
	,active = 0
WHERE
	id IN (205, 206, 424, 425, 498, 499, 532, 533, 548, 549, 550, 551, 552, 553, 564, 565, 574, 575, 576, 577)

UPDATE teleportdescriptions
SET
	sourcecolumnname = 'tp_zone_45_1'
	,targetcolumnname = 'tp_zone_45_2'
WHERE
	id = 319

UPDATE teleportdescriptions
SET
	sourcecolumnname = 'tp_zone_45_2'
	,targetcolumnname = 'tp_zone_45_1'
WHERE
	id = 320


