USE [perpetuumsa]
GO

-----------------------ARTIFACT ALPHA-ZONE BALANCE----------------------
--The alpha zones still have significant pelistal bias in artifactspawninfos
--This flattens the racial biases for Hershfield and New Virginia
--Also fixes other rate/spawn info idiosyncrasies, missing entries, or rates that appear anomalous
--
--This script: A) Inserts one missing artifact type to hershfield (that was found on NV)
--B) Updates the rates of the artifacts from the balance document on the gdrive (changes bolded and highlighted in red)
--Document at OpenPerpetuum-TeamFolders/Economy/Artifacts sheet="ArtifactSpawnInfo - AlphaBalance"
--
--Updates below were generated with:
--SELECT CONCAT('UPDATE artifactspawninfo SET rate=',spawnrate, ' WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note=''',zonenote,''') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name=''',artifacttypename,''');')
--FROM #TEMP_ARTI_SPAWN_INFO
----------------------Revision 2018/12/11---------------------

DECLARE @insert_check bit;
SET @insert_check = 
	CASE 
		WHEN exists (SELECT 1 FROM [artifactspawninfo] WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level2_alpha'))
		THEN 1
		ELSE 0
	END;

IF @insert_check=0
--INSERT missing artifact type to hersh
	INSERT INTO [dbo].[artifactspawninfo]
			   ([artifacttype]
			   ,[zoneid]
			   ,[rate])
		 VALUES
			   ((SELECT TOP 1 id FROM artifacttypes WHERE NAME='industrial_nuimqol_level2_alpha'),
			   (SELECT TOP 1 ID FROM zones WHERE note='hershfield'),
			   4);
ELSE
	PRINT N'INSERT ALREADY RUN! - be careful hotshot';

IF @insert_check=0
	PRINT N'Insert complete, (hopefully without issue)';

GO

--Run updates generated by :
--SELECT CONCAT('UPDATE artifactspawninfo SET rate=',spawnrate, ' WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note=''',zonenote,''') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name=''',artifacttypename,''');')
--FROM #TEMP_ARTI_SPAWN_INFO
--#TEMP_ARTI_SPAWN_INFO is data from the OpenPerpetuum-TeamFolders/Economy/Artifacts sheet="ArtifactSpawnInfo - AlphaBalance" googlesheet
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=1 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=0.5 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=1 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=0.5 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=1 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=0.5 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='new virginia') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='industrial_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='infestation_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=1 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=0.5 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=1 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=0.5 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=1 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=0.5 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='observer_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=12 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=6 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=3 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='salvage_thelodica_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_nuimqol_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_nuimqol_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_nuimqol_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_pelistal_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_pelistal_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_pelistal_level3_alpha');
UPDATE artifactspawninfo SET rate=8 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_thelodica_level1_alpha');
UPDATE artifactspawninfo SET rate=4 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_thelodica_level2_alpha');
UPDATE artifactspawninfo SET rate=2 WHERE zoneid=(SELECT TOP 1 id FROM zones WHERE note='hershfield') AND artifacttype=(SELECT TOP 1 id FROM artifacttypes WHERE artifacttypes.name='science_thelodica_level3_alpha');

GO