USE [perpetuumsa]
GO

--Table of each npc defname and its template+template-relation unqiue parameters
PRINT N'CREATE TEMP TABLE FOR NPC DEFINTION AND 1:1 RELATED DATA';
DROP TABLE IF EXISTS #NPCDEFS;
CREATE TABLE #NPCDEFS(
	defName VARCHAR(100),
	ep INT,
	template VARCHAR(max)
);

INSERT INTO #NPCDEFS (defName, ep, template) VALUES
('def_npc_fivepercent_argano',10,'#robot=ic5#head=i52#chassis=i53#leg=i54#container=i149#headModules=[|m0=[|definition=i32|slot=i1]|m1=[|definition=i33|slot=i2]|m2=[|definition=i2b|slot=i3]]#chassisModules=[|m0=[|definition=i348|slot=i1|ammoDefinition=i984|ammoQuantity=i64]|m1=[|definition=i0|slot=i2]|m2=[|definition=i0|slot=i3]]#legModules=[|m0=[|definition=i32d|slot=i1]|m1=[|definition=i2b5|slot=i2]|m2=[|definition=ie|slot=i3]]'),
('def_npc_fivepercent_Laird',10,'#robot=ic6#head=i55#chassis=i56#leg=i57#container=i149#headModules=[|m0=[|definition=ib1e|slot=i1|ammoDefinition=ib33|ammoQuantity=i5]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]]#chassisModules=[|m0=[|definition=i23|slot=i1]|m1=[|definition=i23|slot=i2]|m2=[|definition=i23|slot=i3]]#legModules=[|m0=[|definition=i29|slot=i1]|m1=[|definition=i29|slot=i2]|m2=[|definition=i286|slot=i3]]'),
('def_npc_tenpercent_castel_rank1',12,'#robot=icc#head=i67#chassis=i68#leg=i69#container=i147#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i31|slot=i3]|m3=[|definition=i32|slot=i4]]#chassisModules=[|m0=[|definition=i3f|slot=i1|ammoDefinition=i98d|ammoQuantity=i64]|m1=[|definition=i3f|slot=i2|ammoDefinition=i98d|ammoQuantity=i64]|m2=[|definition=i3f|slot=i3|ammoDefinition=i98e|ammoQuantity=i64]|m3=[|definition=i3f|slot=i4|ammoDefinition=i98e|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]]'),
('def_npc_tenpercent_yagel_rank1',12,'#robot=ic1#head=i46#chassis=i47#leg=i48#container=i147#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=i981|ammoQuantity=i64]|m1=[|definition=i42|slot=i2|ammoDefinition=i980|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=i981|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=i980|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i285|slot=i3]|m3=[|definition=i29|slot=i4]]'),
('def_npc_tenpercent_prom_rank1',12,'#robot=ic2#head=i49#chassis=i4a#leg=i4b#container=i147#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]]#chassisModules=[|m0=[|definition=i39|slot=i1|ammoDefinition=i989|ammoQuantity=i64]|m1=[|definition=i39|slot=i2|ammoDefinition=i989|ammoQuantity=i64]|m2=[|definition=i39|slot=i3|ammoDefinition=i98a|ammoQuantity=i64]|m3=[|definition=i39|slot=i4|ammoDefinition=i98a|ammoQuantity=i64]]#legModules=[|m0=[|definition=i12|slot=i1]|m1=[|definition=ie|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]]'),
('def_npc_tenpercent_prom_rank2',13,'#robot=ic2#head=i49#chassis=i4a#leg=i4b#container=i147#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]]#chassisModules=[|m0=[|definition=i39|slot=i1|ammoDefinition=i989|ammoQuantity=i64]|m1=[|definition=i39|slot=i2|ammoDefinition=i989|ammoQuantity=i64]|m2=[|definition=i39|slot=i3|ammoDefinition=i98a|ammoQuantity=i64]|m3=[|definition=i39|slot=i4|ammoDefinition=i98a|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]]'),
('def_npc_tenpercent_castel_rank2',13,'#robot=icc#head=i67#chassis=i68#leg=i69#container=i147#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i31|slot=i3]|m3=[|definition=i32|slot=i4]]#chassisModules=[|m0=[|definition=i3f|slot=i1|ammoDefinition=i98d|ammoQuantity=i0]|m1=[|definition=i3f|slot=i2|ammoDefinition=i98d|ammoQuantity=i0]|m2=[|definition=i3f|slot=i3|ammoDefinition=i98e|ammoQuantity=i0]|m3=[|definition=i3f|slot=i4|ammoDefinition=i98e|ammoQuantity=i0]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]]'),
('def_npc_tenpercent_yagel_rank2',13,'#robot=ic1#head=i46#chassis=i47#leg=i48#container=i147#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=if8|ammoQuantity=i64]|m1=[|definition=i42|slot=i2|ammoDefinition=if7|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=if8|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=if7|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i285|slot=i3]|m3=[|definition=i29|slot=i4]]'),
('def_npc_percent_wasp_rank2',16,'#robot=ic4#head=i4f#chassis=i50#leg=i51#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]|m3=[|definition=i1636|slot=i4]|m4=[|definition=i0|slot=i5]]#chassisModules=[|m0=[|definition=i3f|slot=i1|ammoDefinition=i98d|ammoQuantity=i64]|m1=[|definition=i3f|slot=i2|ammoDefinition=i98d|ammoQuantity=i64]|m2=[|definition=i3f|slot=i3|ammoDefinition=i98d|ammoQuantity=i64]|m3=[|definition=i3f|slot=i4|ammoDefinition=i98d|ammoQuantity=i64]|m4=[|definition=i3f|slot=i5|ammoDefinition=i98d|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]]'),
('def_npc_percent_baph_rank2',16,'#robot=ica#head=i61#chassis=i62#leg=i63#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]|m3=[|definition=i38f|slot=i4]|m4=[|definition=i38f|slot=i5]]#chassisModules=[|m0=[|definition=i39|slot=i1|ammoDefinition=i989|ammoQuantity=i64]|m1=[|definition=i39|slot=i2|ammoDefinition=i989|ammoQuantity=i64]|m2=[|definition=i39|slot=i3|ammoDefinition=i989|ammoQuantity=i64]|m3=[|definition=i39|slot=i4|ammoDefinition=i98a|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_arby_rank2',16,'#robot=ic9#head=i5e#chassis=i5f#leg=i60#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]|m3=[|definition=ib1e|slot=i4|ammoDefinition=ib33|ammoQuantity=ia]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=i980|ammoQuantity=i64]|m1=[|definition=i42|slot=i2|ammoDefinition=i980|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=i980|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=i981|ammoQuantity=i64]|m4=[|definition=i42|slot=i5|ammoDefinition=i981|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_arby_rank3',18,'#robot=ic9#head=i5e#chassis=i5f#leg=i60#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=ib1e|slot=i6|ammoDefinition=ib33|ammoQuantity=ia]|m3=[|definition=i33|slot=i6]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=i980|ammoQuantity=i64]|m1=[|definition=i42|slot=i2|ammoDefinition=i980|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=i980|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=i981|ammoQuantity=i64]|m4=[|definition=i42|slot=i5|ammoDefinition=i981|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_baph_rank3',18,'#robot=ic9#head=i5e#chassis=i5f#leg=i60#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=ib1e|slot=i6|ammoDefinition=ib33|ammoQuantity=ia]|m3=[|definition=i33|slot=i6]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=i980|ammoQuantity=i64]|m1=[|definition=i42|slot=i2|ammoDefinition=i980|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=i980|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=i981|ammoQuantity=i64]|m4=[|definition=i42|slot=i5|ammoDefinition=i981|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_wasp_rank3',18,'#robot=ic9#head=i5e#chassis=i5f#leg=i60#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=ib1e|slot=i6|ammoDefinition=ib33|ammoQuantity=ia]|m3=[|definition=i33|slot=i6]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=i980|ammoQuantity=i64]|m1=[|definition=i42|slot=i2|ammoDefinition=i980|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=i980|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=i981|ammoQuantity=i64]|m4=[|definition=i42|slot=i5|ammoDefinition=i981|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_wasp_rank4',20,'#robot=ic4#head=i4f#chassis=i50#leg=i51#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]|m3=[|definition=i1636|slot=i4]|m4=[|definition=i0|slot=i5]]#chassisModules=[|m0=[|definition=i3f|slot=i1|ammoDefinition=i98d|ammoQuantity=i64]|m1=[|definition=i3f|slot=i2|ammoDefinition=i98d|ammoQuantity=i64]|m2=[|definition=i3f|slot=i3|ammoDefinition=i98d|ammoQuantity=i64]|m3=[|definition=i3f|slot=i4|ammoDefinition=i98e|ammoQuantity=i64]|m4=[|definition=i3f|slot=i5|ammoDefinition=i98e|ammoQuantity=i64]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i12a|slot=i3]|m3=[|definition=i285|slot=i4]]'),
('def_npc_percent_baph_rank4',20,'#robot=ica#head=i61#chassis=i62#leg=i63#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]|m3=[|definition=i38f|slot=i4]|m4=[|definition=i38f|slot=i5]]#chassisModules=[|m0=[|definition=i39|slot=i1|ammoDefinition=i989|ammoQuantity=i64]|m1=[|definition=i39|slot=i2|ammoDefinition=i989|ammoQuantity=i64]|m2=[|definition=i39|slot=i3|ammoDefinition=i989|ammoQuantity=i64]|m3=[|definition=i39|slot=i4|ammoDefinition=i98a|ammoQuantity=i64]|m4=[|definition=i39|slot=i5|ammoDefinition=i98a|ammoQuantity=i64]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_arby_rank4',20,'#robot=ic9#head=i5e#chassis=i5f#leg=i60#container=i148#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i32|slot=i2]|m2=[|definition=i33|slot=i3]|m3=[|definition=ib1e|slot=i4|ammoDefinition=ib33|ammoQuantity=ia]]#chassisModules=[|m0=[|definition=i42|slot=i1|ammoDefinition=i980|ammoQuantity=i8c]|m1=[|definition=i42|slot=i2|ammoDefinition=i980|ammoQuantity=i64]|m2=[|definition=i42|slot=i3|ammoDefinition=i980|ammoQuantity=i64]|m3=[|definition=i42|slot=i4|ammoDefinition=i981|ammoQuantity=i64]|m4=[|definition=i42|slot=i5|ammoDefinition=i981|ammoQuantity=i64]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=ie|slot=i1]|m1=[|definition=i12|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i12a|slot=i4]|m4=[|definition=i285|slot=i5]]'),
('def_npc_percent_kain_rank3',25,'#robot=icd#head=i6a#chassis=i6b#leg=i6c#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i38d|slot=i2]|m2=[|definition=i38d|slot=i3]|m3=[|definition=i38d|slot=i4]]#chassisModules=[|m0=[|definition=i43|slot=i1|ammoDefinition=i982|ammoQuantity=i64]|m1=[|definition=i43|slot=i2|ammoDefinition=i982|ammoQuantity=i64]|m2=[|definition=i43|slot=i3|ammoDefinition=i982|ammoQuantity=i64]|m3=[|definition=i43|slot=i4|ammoDefinition=i982|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i18|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i1b|slot=i5]]'),
('def_npc_percent_kain_rank4',28,'#robot=icd#head=i6a#chassis=i6b#leg=i6c#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i38d|slot=i2]|m2=[|definition=i38d|slot=i3]|m3=[|definition=i38d|slot=i4]]#chassisModules=[|m0=[|definition=i43|slot=i1|ammoDefinition=i982|ammoQuantity=i64]|m1=[|definition=i43|slot=i2|ammoDefinition=i982|ammoQuantity=i64]|m2=[|definition=i43|slot=i3|ammoDefinition=i982|ammoQuantity=i64]|m3=[|definition=i43|slot=i4|ammoDefinition=i982|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i18|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i1b|slot=i5]]'),
('def_npc_percent_kain_rank5',30,'#robot=icd#head=i6a#chassis=i6b#leg=i6c#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i38d|slot=i2]|m2=[|definition=i38d|slot=i3]|m3=[|definition=i38d|slot=i4]]#chassisModules=[|m0=[|definition=i43|slot=i1|ammoDefinition=i982|ammoQuantity=i64]|m1=[|definition=i43|slot=i2|ammoDefinition=i982|ammoQuantity=i64]|m2=[|definition=i43|slot=i3|ammoDefinition=i982|ammoQuantity=i64]|m3=[|definition=i43|slot=i4|ammoDefinition=i982|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i18|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i1b|slot=i5]]'),
('def_npc_percent_arty_rank5',30,'#robot=ice#head=i6d#chassis=i6e#leg=i6f#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=i38f|slot=i5]]#chassisModules=[|m0=[|definition=i3a|slot=i1|ammoDefinition=i98b|ammoQuantity=i64]|m1=[|definition=i3a|slot=i2|ammoDefinition=i98b|ammoQuantity=i64]|m2=[|definition=i3a|slot=i3|ammoDefinition=i98b|ammoQuantity=i64]|m3=[|definition=i3a|slot=i4|ammoDefinition=i98b|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i19|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i1b|slot=i5]]'),
('def_npc_percent_arty_rank4',28,'#robot=ice#head=i6d#chassis=i6e#leg=i6f#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=i38f|slot=i5]]#chassisModules=[|m0=[|definition=i3a|slot=i1|ammoDefinition=i98b|ammoQuantity=i64]|m1=[|definition=i3a|slot=i2|ammoDefinition=i98b|ammoQuantity=i64]|m2=[|definition=i3a|slot=i3|ammoDefinition=i98b|ammoQuantity=i64]|m3=[|definition=i3a|slot=i4|ammoDefinition=i98b|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i19|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i1b|slot=i5]]'),
('def_npc_percent_arty_rank3',25,'#robot=ice#head=i6d#chassis=i6e#leg=i6f#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=i38f|slot=i5]]#chassisModules=[|m0=[|definition=i3a|slot=i1|ammoDefinition=i98b|ammoQuantity=i64]|m1=[|definition=i3a|slot=i2|ammoDefinition=i98b|ammoQuantity=i64]|m2=[|definition=i3a|slot=i3|ammoDefinition=i98b|ammoQuantity=i64]|m3=[|definition=i3a|slot=i4|ammoDefinition=i98b|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i19|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i1b|slot=i5]]'),
('def_npc_percent_tyro_rank3',25,'#robot=id0#head=i73#chassis=i74#leg=i75#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=ib52|slot=i5]]#chassisModules=[|m0=[|definition=i40|slot=i1|ammoDefinition=i992|ammoQuantity=i64]|m1=[|definition=i40|slot=i2|ammoDefinition=i992|ammoQuantity=i64]|m2=[|definition=i40|slot=i3|ammoDefinition=i992|ammoQuantity=i64]|m3=[|definition=i40|slot=i4|ammoDefinition=i992|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i286|slot=i4]]'),
('def_npc_percent_tyro_rank4',28,'#robot=id0#head=i73#chassis=i74#leg=i75#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=ib52|slot=i5]]#chassisModules=[|m0=[|definition=i40|slot=i1|ammoDefinition=i992|ammoQuantity=i64]|m1=[|definition=i40|slot=i2|ammoDefinition=i992|ammoQuantity=i64]|m2=[|definition=i40|slot=i3|ammoDefinition=i992|ammoQuantity=i64]|m3=[|definition=i40|slot=i4|ammoDefinition=i992|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i29|slot=i3]|m3=[|definition=i286|slot=i4]]'),
('def_npc_percent_tyro_rank5',30,'#robot=id0#head=i73#chassis=i74#leg=i75#container=i14a#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=ib52|slot=i5]]#chassisModules=[|m0=[|definition=i40|slot=i1|ammoDefinition=i992|ammoQuantity=i64]|m1=[|definition=i40|slot=i2|ammoDefinition=i992|ammoQuantity=i64]|m2=[|definition=i40|slot=i3|ammoDefinition=i992|ammoQuantity=i64]|m3=[|definition=i40|slot=i4|ammoDefinition=i992|ammoQuantity=i64]|m4=[|definition=i0|slot=i5]|m5=[|definition=i0|slot=i6]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i13|slot=i2]|m2=[|definition=i289|slot=i3]|m3=[|definition=i29|slot=i4]]'),
('def_npc_percent_gropho_rank5',40,'#robot=id8#head=i8b#chassis=i8c#leg=i8d#container=i14c#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i391|slot=i3]|m3=[|definition=i391|slot=i4]|m4=[|definition=i38e|slot=i5]|m5=[|definition=i38e|slot=i6]]#chassisModules=[|m0=[|definition=i40|slot=i1|ammoDefinition=i991|ammoQuantity=i64]|m1=[|definition=i40|slot=i2|ammoDefinition=i991|ammoQuantity=i64]|m2=[|definition=i40|slot=i3|ammoDefinition=i991|ammoQuantity=i64]|m3=[|definition=i40|slot=i4|ammoDefinition=i991|ammoQuantity=i64]|m4=[|definition=i40|slot=i5|ammoDefinition=i991|ammoQuantity=i64]|m5=[|definition=i40|slot=i6|ammoDefinition=i991|ammoQuantity=i64]|m6=[|definition=i0|slot=i7]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i10|slot=i2]|m2=[|definition=i13|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i19|slot=i5]]'),
('def_npc_percent_gropho_rank4',35,'#robot=id8#head=i8b#chassis=i8c#leg=i8d#container=i14c#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i38e|slot=i3]|m3=[|definition=i38e|slot=i4]|m4=[|definition=i391|slot=i5]|m5=[|definition=i391|slot=i6]]#chassisModules=[|m0=[|definition=i40|slot=i1|ammoDefinition=i991|ammoQuantity=i64]|m1=[|definition=i40|slot=i2|ammoDefinition=i991|ammoQuantity=i64]|m2=[|definition=i40|slot=i3|ammoDefinition=i991|ammoQuantity=i64]|m3=[|definition=i40|slot=i4|ammoDefinition=i991|ammoQuantity=i64]|m4=[|definition=i40|slot=i5|ammoDefinition=i991|ammoQuantity=i64]|m5=[|definition=i40|slot=i6|ammoDefinition=i991|ammoQuantity=i64]|m6=[|definition=i0|slot=i7]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i10|slot=i2]|m2=[|definition=i13|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i19|slot=i5]]'),
('def_npc_percent_seth_rank4',35,'#robot=id6#head=i85#chassis=i86#leg=i87#container=i14c#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i38f|slot=i3]|m3=[|definition=i38f|slot=i4]|m4=[|definition=i38f|slot=i5]|m5=[|definition=i38f|slot=i6]]#chassisModules=[|m0=[|definition=i3a|slot=i1|ammoDefinition=i98b|ammoQuantity=i64]|m1=[|definition=i3a|slot=i2|ammoDefinition=i98b|ammoQuantity=i64]|m2=[|definition=i3a|slot=i3|ammoDefinition=i98b|ammoQuantity=i64]|m3=[|definition=i3a|slot=i4|ammoDefinition=i98b|ammoQuantity=i64]|m4=[|definition=i3a|slot=i5|ammoDefinition=i98b|ammoQuantity=i64]|m5=[|definition=i3a|slot=i6|ammoDefinition=i98b|ammoQuantity=i64]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i10|slot=i2]|m2=[|definition=i13|slot=i3]|m3=[|definition=i29|slot=i4]|m4=[|definition=i286|slot=i5]|m5=[|definition=i1b|slot=i6]]'),
('def_npc_percent_seth_rank5',40,'#robot=id6#head=i85#chassis=i86#leg=i87#container=i14c#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i38f|slot=i3]|m3=[|definition=i38f|slot=i4]|m4=[|definition=i38f|slot=i5]|m5=[|definition=i38f|slot=i6]]#chassisModules=[|m0=[|definition=i3a|slot=i1|ammoDefinition=i98b|ammoQuantity=i64]|m1=[|definition=i3a|slot=i2|ammoDefinition=i98b|ammoQuantity=i64]|m2=[|definition=i3a|slot=i3|ammoDefinition=i98b|ammoQuantity=i64]|m3=[|definition=i3a|slot=i4|ammoDefinition=i98b|ammoQuantity=i64]|m4=[|definition=i3a|slot=i5|ammoDefinition=i98b|ammoQuantity=i64]|m5=[|definition=i3a|slot=i6|ammoDefinition=i98b|ammoQuantity=i64]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i10|slot=i2]|m2=[|definition=i13|slot=i3]|m3=[|definition=i286|slot=i4]|m4=[|definition=i29|slot=i5]|m5=[|definition=i1b|slot=i6]]'),
('def_npc_percent_mesmer_rank5',40,'#robot=id5#head=i82#chassis=i83#leg=i84#container=i14c#headModules=[|m0=[|definition=i424|slot=i1]|m1=[|definition=i424|slot=i2]|m2=[|definition=i424|slot=i3]|m3=[|definition=i424|slot=i4]|m4=[|definition=i31|slot=i5]]#chassisModules=[|m0=[|definition=i43|slot=i1|ammoDefinition=i982|ammoQuantity=i64]|m1=[|definition=i43|slot=i2|ammoDefinition=i982|ammoQuantity=i64]|m2=[|definition=i43|slot=i3|ammoDefinition=i982|ammoQuantity=i64]|m3=[|definition=i43|slot=i4|ammoDefinition=i982|ammoQuantity=i64]|m4=[|definition=i43|slot=i5|ammoDefinition=i982|ammoQuantity=i64]|m5=[|definition=i43|slot=i6|ammoDefinition=i982|ammoQuantity=i64]|m6=[|definition=i0|slot=i7]]#legModules=[|m0=[|definition=i286|slot=i1]|m1=[|definition=i286|slot=i2]|m2=[|definition=i289|slot=i3]|m3=[|definition=i13|slot=i4]|m4=[|definition=i13|slot=i5]|m5=[|definition=i13|slot=i6]]'),
('def_npc_percent_mesmer_rank4',35,'#robot=id8#head=i8b#chassis=i8c#leg=i8d#container=i14c#headModules=[|m0=[|definition=i2b|slot=i1]|m1=[|definition=i2b|slot=i2]|m2=[|definition=i38e|slot=i3]|m3=[|definition=i38e|slot=i4]|m4=[|definition=i391|slot=i5]|m5=[|definition=i391|slot=i6]]#chassisModules=[|m0=[|definition=i40|slot=i1|ammoDefinition=i991|ammoQuantity=i64]|m1=[|definition=i40|slot=i2|ammoDefinition=i991|ammoQuantity=i64]|m2=[|definition=i40|slot=i3|ammoDefinition=i991|ammoQuantity=i64]|m3=[|definition=i40|slot=i4|ammoDefinition=i991|ammoQuantity=i64]|m4=[|definition=i40|slot=i5|ammoDefinition=i991|ammoQuantity=i64]|m5=[|definition=i40|slot=i6|ammoDefinition=i991|ammoQuantity=i64]|m6=[|definition=i0|slot=i7]]#legModules=[|m0=[|definition=i10|slot=i1]|m1=[|definition=i10|slot=i2]|m2=[|definition=i13|slot=i3]|m3=[|definition=i1a|slot=i4]|m4=[|definition=i19|slot=i5]]');


PRINT N'CREATE TEMP TABLE FOR NPC MODIFIERS (aggregatevalues)';
DROP TABLE IF EXISTS #NPCMODS
CREATE TABLE #NPCMODS 
(
	defName VARCHAR(100),
	fieldName VARCHAR(100),
	fieldValue FLOAT,
);
INSERT INTO #NPCMODS (defName, fieldName, fieldValue) VALUES
('def_npc_fivepercent_argano','armor_max_modifier',0.6),
('def_npc_fivepercent_argano','armor_repair_amount_modifier',0.5),
('def_npc_fivepercent_argano','cpu_max_modifier',2),
('def_npc_fivepercent_argano','damage_modifier',0.6),
('def_npc_fivepercent_argano','missile_cycle_time_modifier',1.2),
('def_npc_fivepercent_argano','powergrid_max_modifier',2),
('def_npc_fivepercent_argano','speed_max_modifier',0.4),
('def_npc_fivepercent_argano','turret_cycle_time_modifier',1.4),
('def_npc_fivepercent_argano','received_repaired_modifier',0.1),
('def_npc_fivepercent_Laird','armor_max_modifier',0.6),
('def_npc_fivepercent_Laird','armor_repair_amount_modifier',0.5),
('def_npc_fivepercent_Laird','cpu_max_modifier',2),
('def_npc_fivepercent_Laird','damage_modifier',0.6),
('def_npc_fivepercent_Laird','missile_cycle_time_modifier',1.2),
('def_npc_fivepercent_Laird','powergrid_max_modifier',2),
('def_npc_fivepercent_Laird','speed_max_modifier',0.4),
('def_npc_fivepercent_Laird','turret_cycle_time_modifier',1.4),
('def_npc_fivepercent_Laird','received_repaired_modifier',0.1),
('def_npc_tenpercent_castel_rank1','armor_max_modifier',0.6),
('def_npc_tenpercent_castel_rank1','armor_repair_amount_modifier',0.5),
('def_npc_tenpercent_castel_rank1','cpu_max_modifier',2),
('def_npc_tenpercent_castel_rank1','damage_modifier',0.6),
('def_npc_tenpercent_castel_rank1','missile_cycle_time_modifier',1.2),
('def_npc_tenpercent_castel_rank1','powergrid_max_modifier',2),
('def_npc_tenpercent_castel_rank1','speed_max_modifier',0.4),
('def_npc_tenpercent_castel_rank1','turret_cycle_time_modifier',1.4),
('def_npc_tenpercent_castel_rank1','received_repaired_modifier',0.1),
('def_npc_tenpercent_yagel_rank1','armor_max_modifier',0.6),
('def_npc_tenpercent_yagel_rank1','armor_repair_amount_modifier',0.5),
('def_npc_tenpercent_yagel_rank1','cpu_max_modifier',2),
('def_npc_tenpercent_yagel_rank1','damage_modifier',0.6),
('def_npc_tenpercent_yagel_rank1','missile_cycle_time_modifier',1.2),
('def_npc_tenpercent_yagel_rank1','powergrid_max_modifier',2),
('def_npc_tenpercent_yagel_rank1','speed_max_modifier',0.4),
('def_npc_tenpercent_yagel_rank1','turret_cycle_time_modifier',1.4),
('def_npc_tenpercent_yagel_rank1','received_repaired_modifier',0.1),
('def_npc_tenpercent_prom_rank1','armor_max_modifier',0.6),
('def_npc_tenpercent_prom_rank1','armor_repair_amount_modifier',0.5),
('def_npc_tenpercent_prom_rank1','cpu_max_modifier',2),
('def_npc_tenpercent_prom_rank1','damage_modifier',0.6),
('def_npc_tenpercent_prom_rank1','missile_cycle_time_modifier',1.2),
('def_npc_tenpercent_prom_rank1','powergrid_max_modifier',2),
('def_npc_tenpercent_prom_rank1','speed_max_modifier',0.4),
('def_npc_tenpercent_prom_rank1','turret_cycle_time_modifier',1.4),
('def_npc_tenpercent_prom_rank1','received_repaired_modifier',0.1),
('def_npc_tenpercent_prom_rank2','armor_max_modifier',0.95),
('def_npc_tenpercent_prom_rank2','cpu_max_modifier',2),
('def_npc_tenpercent_prom_rank2','optimal_range_modifier',1.1),
('def_npc_tenpercent_prom_rank2','powergrid_max_modifier',2),
('def_npc_tenpercent_prom_rank2','speed_max_modifier',0.8),
('def_npc_tenpercent_prom_rank2','received_repaired_modifier',0.1),
('def_npc_tenpercent_castel_rank2','armor_max_modifier',0.95),
('def_npc_tenpercent_castel_rank2','cpu_max_modifier',2),
('def_npc_tenpercent_castel_rank2','optimal_range_modifier',1.1),
('def_npc_tenpercent_castel_rank2','powergrid_max_modifier',2),
('def_npc_tenpercent_castel_rank2','speed_max_modifier',0.8),
('def_npc_tenpercent_castel_rank2','received_repaired_modifier',0.1),
('def_npc_tenpercent_yagel_rank2','armor_max_modifier',0.95),
('def_npc_tenpercent_yagel_rank2','cpu_max_modifier',2),
('def_npc_tenpercent_yagel_rank2','optimal_range_modifier',1.1),
('def_npc_tenpercent_yagel_rank2','powergrid_max_modifier',2),
('def_npc_tenpercent_yagel_rank2','speed_max_modifier',0.8),
('def_npc_tenpercent_yagel_rank2','received_repaired_modifier',0.1),
('def_npc_percent_wasp_rank2','armor_max_modifier',0.95),
('def_npc_percent_wasp_rank2','cpu_max_modifier',2),
('def_npc_percent_wasp_rank2','optimal_range_modifier',1.1),
('def_npc_percent_wasp_rank2','powergrid_max_modifier',2),
('def_npc_percent_wasp_rank2','speed_max_modifier',0.8),
('def_npc_percent_wasp_rank2','received_repaired_modifier',0.1),
('def_npc_percent_baph_rank2','armor_max_modifier',0.95),
('def_npc_percent_baph_rank2','cpu_max_modifier',2),
('def_npc_percent_baph_rank2','optimal_range_modifier',1.1),
('def_npc_percent_baph_rank2','powergrid_max_modifier',2),
('def_npc_percent_baph_rank2','speed_max_modifier',0.8),
('def_npc_percent_baph_rank2','received_repaired_modifier',0.1),
('def_npc_percent_arby_rank2','armor_max_modifier',0.95),
('def_npc_percent_arby_rank2','cpu_max_modifier',2),
('def_npc_percent_arby_rank2','optimal_range_modifier',1.1),
('def_npc_percent_arby_rank2','powergrid_max_modifier',2),
('def_npc_percent_arby_rank2','speed_max_modifier',0.8),
('def_npc_percent_arby_rank2','received_repaired_modifier',0.1),
('def_npc_percent_arby_rank3','armor_max_modifier',1.3),
('def_npc_percent_arby_rank3','core_max_modifier',1.2),
('def_npc_percent_arby_rank3','core_recharge_time_modifier',0.8),
('def_npc_percent_arby_rank3','cpu_max_modifier',2),
('def_npc_percent_arby_rank3','damage_modifier',1.2),
('def_npc_percent_arby_rank3','falloff_modifier',1.2),
('def_npc_percent_arby_rank3','locking_range_modifier',1.1),
('def_npc_percent_arby_rank3','locking_time_modifier',0.9),
('def_npc_percent_arby_rank3','missile_cycle_time_modifier',0.9),
('def_npc_percent_arby_rank3','optimal_range_modifier',1.2),
('def_npc_percent_arby_rank3','powergrid_max_modifier',2),
('def_npc_percent_arby_rank3','turret_cycle_time_modifier',0.9),
('def_npc_percent_arby_rank3','received_repaired_modifier',0.1),
('def_npc_percent_baph_rank3','armor_max_modifier',1.3),
('def_npc_percent_baph_rank3','core_max_modifier',1.2),
('def_npc_percent_baph_rank3','core_recharge_time_modifier',0.8),
('def_npc_percent_baph_rank3','cpu_max_modifier',2),
('def_npc_percent_baph_rank3','damage_modifier',1.2),
('def_npc_percent_baph_rank3','falloff_modifier',1.2),
('def_npc_percent_baph_rank3','locking_range_modifier',1.1),
('def_npc_percent_baph_rank3','locking_time_modifier',0.9),
('def_npc_percent_baph_rank3','missile_cycle_time_modifier',0.9),
('def_npc_percent_baph_rank3','optimal_range_modifier',1.2),
('def_npc_percent_baph_rank3','powergrid_max_modifier',2),
('def_npc_percent_baph_rank3','turret_cycle_time_modifier',0.9),
('def_npc_percent_baph_rank3','received_repaired_modifier',0.1),
('def_npc_percent_wasp_rank3','armor_max_modifier',1.3),
('def_npc_percent_wasp_rank3','core_max_modifier',1.2),
('def_npc_percent_wasp_rank3','core_recharge_time_modifier',0.8),
('def_npc_percent_wasp_rank3','cpu_max_modifier',2),
('def_npc_percent_wasp_rank3','damage_modifier',1.2),
('def_npc_percent_wasp_rank3','falloff_modifier',1.2),
('def_npc_percent_wasp_rank3','locking_range_modifier',1.1),
('def_npc_percent_wasp_rank3','locking_time_modifier',0.9),
('def_npc_percent_wasp_rank3','missile_cycle_time_modifier',0.9),
('def_npc_percent_wasp_rank3','optimal_range_modifier',1.2),
('def_npc_percent_wasp_rank3','powergrid_max_modifier',2),
('def_npc_percent_wasp_rank3','turret_cycle_time_modifier',0.9),
('def_npc_percent_wasp_rank3','received_repaired_modifier',0.1),
('def_npc_percent_wasp_rank4','armor_max_modifier',1.5),
('def_npc_percent_wasp_rank4','core_max_modifier',1.3),
('def_npc_percent_wasp_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_wasp_rank4','cpu_max_modifier',2),
('def_npc_percent_wasp_rank4','damage_modifier',1.3),
('def_npc_percent_wasp_rank4','falloff_modifier',1.3),
('def_npc_percent_wasp_rank4','locking_range_modifier',1.1),
('def_npc_percent_wasp_rank4','locking_time_modifier',0.9),
('def_npc_percent_wasp_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_wasp_rank4','optimal_range_modifier',1.3),
('def_npc_percent_wasp_rank4','powergrid_max_modifier',2),
('def_npc_percent_wasp_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_wasp_rank4','received_repaired_modifier',0.1),
('def_npc_percent_baph_rank4','armor_max_modifier',1.5),
('def_npc_percent_baph_rank4','core_max_modifier',1.3),
('def_npc_percent_baph_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_baph_rank4','cpu_max_modifier',2),
('def_npc_percent_baph_rank4','damage_modifier',1.3),
('def_npc_percent_baph_rank4','falloff_modifier',1.3),
('def_npc_percent_baph_rank4','locking_range_modifier',1.1),
('def_npc_percent_baph_rank4','locking_time_modifier',0.9),
('def_npc_percent_baph_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_baph_rank4','optimal_range_modifier',1.3),
('def_npc_percent_baph_rank4','powergrid_max_modifier',2),
('def_npc_percent_baph_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_baph_rank4','received_repaired_modifier',0.1),
('def_npc_percent_arby_rank4','armor_max_modifier',1.5),
('def_npc_percent_arby_rank4','core_max_modifier',1.3),
('def_npc_percent_arby_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_arby_rank4','cpu_max_modifier',2),
('def_npc_percent_arby_rank4','damage_modifier',1.3),
('def_npc_percent_arby_rank4','falloff_modifier',1.3),
('def_npc_percent_arby_rank4','locking_range_modifier',1.1),
('def_npc_percent_arby_rank4','locking_time_modifier',0.9),
('def_npc_percent_arby_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_arby_rank4','optimal_range_modifier',1.3),
('def_npc_percent_arby_rank4','powergrid_max_modifier',2),
('def_npc_percent_arby_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_arby_rank4','received_repaired_modifier',0.1),
('def_npc_percent_kain_rank3','armor_max_modifier',1.3),
('def_npc_percent_kain_rank3','core_max_modifier',1.2),
('def_npc_percent_kain_rank3','core_recharge_time_modifier',0.8),
('def_npc_percent_kain_rank3','cpu_max_modifier',2),
('def_npc_percent_kain_rank3','damage_modifier',1.2),
('def_npc_percent_kain_rank3','falloff_modifier',1.2),
('def_npc_percent_kain_rank3','locking_range_modifier',1.1),
('def_npc_percent_kain_rank3','locking_time_modifier',0.9),
('def_npc_percent_kain_rank3','missile_cycle_time_modifier',0.9),
('def_npc_percent_kain_rank3','optimal_range_modifier',1.2),
('def_npc_percent_kain_rank3','powergrid_max_modifier',2),
('def_npc_percent_kain_rank3','turret_cycle_time_modifier',0.9),
('def_npc_percent_kain_rank3','received_repaired_modifier',0.1),
('def_npc_percent_kain_rank4','armor_max_modifier',1.5),
('def_npc_percent_kain_rank4','core_max_modifier',1.3),
('def_npc_percent_kain_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_kain_rank4','cpu_max_modifier',2),
('def_npc_percent_kain_rank4','damage_modifier',1.3),
('def_npc_percent_kain_rank4','falloff_modifier',1.3),
('def_npc_percent_kain_rank4','locking_range_modifier',1.1),
('def_npc_percent_kain_rank4','locking_time_modifier',0.9),
('def_npc_percent_kain_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_kain_rank4','optimal_range_modifier',1.3),
('def_npc_percent_kain_rank4','powergrid_max_modifier',2),
('def_npc_percent_kain_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_kain_rank4','received_repaired_modifier',0.1),
('def_npc_percent_kain_rank5','armor_max_modifier',1.7),
('def_npc_percent_kain_rank5','core_max_modifier',1.5),
('def_npc_percent_kain_rank5','core_recharge_time_modifier',0.7),
('def_npc_percent_kain_rank5','cpu_max_modifier',2),
('def_npc_percent_kain_rank5','damage_modifier',1.5),
('def_npc_percent_kain_rank5','falloff_modifier',1.3),
('def_npc_percent_kain_rank5','locking_range_modifier',1.5),
('def_npc_percent_kain_rank5','locking_time_modifier',0.7),
('def_npc_percent_kain_rank5','missile_cycle_time_modifier',0.7),
('def_npc_percent_kain_rank5','optimal_range_modifier',1.3),
('def_npc_percent_kain_rank5','powergrid_max_modifier',2),
('def_npc_percent_kain_rank5','turret_cycle_time_modifier',0.7),
('def_npc_percent_kain_rank5','received_repaired_modifier',0.1),
('def_npc_percent_arty_rank5','armor_max_modifier',1.7),
('def_npc_percent_arty_rank5','core_max_modifier',1.5),
('def_npc_percent_arty_rank5','core_recharge_time_modifier',0.7),
('def_npc_percent_arty_rank5','cpu_max_modifier',2),
('def_npc_percent_arty_rank5','damage_modifier',1.5),
('def_npc_percent_arty_rank5','falloff_modifier',1.3),
('def_npc_percent_arty_rank5','locking_range_modifier',1.5),
('def_npc_percent_arty_rank5','locking_time_modifier',0.7),
('def_npc_percent_arty_rank5','missile_cycle_time_modifier',0.7),
('def_npc_percent_arty_rank5','optimal_range_modifier',1.3),
('def_npc_percent_arty_rank5','powergrid_max_modifier',2),
('def_npc_percent_arty_rank5','turret_cycle_time_modifier',0.7),
('def_npc_percent_arty_rank5','received_repaired_modifier',0.1),
('def_npc_percent_arty_rank4','armor_max_modifier',1.5),
('def_npc_percent_arty_rank4','core_max_modifier',1.3),
('def_npc_percent_arty_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_arty_rank4','cpu_max_modifier',2),
('def_npc_percent_arty_rank4','damage_modifier',1.3),
('def_npc_percent_arty_rank4','falloff_modifier',1.3),
('def_npc_percent_arty_rank4','locking_range_modifier',1.1),
('def_npc_percent_arty_rank4','locking_time_modifier',0.9),
('def_npc_percent_arty_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_arty_rank4','optimal_range_modifier',1.3),
('def_npc_percent_arty_rank4','powergrid_max_modifier',2),
('def_npc_percent_arty_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_arty_rank4','received_repaired_modifier',0.1),
('def_npc_percent_arty_rank3','armor_max_modifier',1.3),
('def_npc_percent_arty_rank3','core_max_modifier',1.2),
('def_npc_percent_arty_rank3','core_recharge_time_modifier',0.8),
('def_npc_percent_arty_rank3','cpu_max_modifier',2),
('def_npc_percent_arty_rank3','damage_modifier',1.2),
('def_npc_percent_arty_rank3','falloff_modifier',1.2),
('def_npc_percent_arty_rank3','locking_range_modifier',1.1),
('def_npc_percent_arty_rank3','locking_time_modifier',0.9),
('def_npc_percent_arty_rank3','missile_cycle_time_modifier',0.9),
('def_npc_percent_arty_rank3','optimal_range_modifier',1.2),
('def_npc_percent_arty_rank3','powergrid_max_modifier',2),
('def_npc_percent_arty_rank3','turret_cycle_time_modifier',0.9),
('def_npc_percent_arty_rank3','received_repaired_modifier',0.1),
('def_npc_percent_tyro_rank3','armor_max_modifier',1.3),
('def_npc_percent_tyro_rank3','core_max_modifier',1.2),
('def_npc_percent_tyro_rank3','core_recharge_time_modifier',0.8),
('def_npc_percent_tyro_rank3','cpu_max_modifier',2),
('def_npc_percent_tyro_rank3','damage_modifier',1.2),
('def_npc_percent_tyro_rank3','falloff_modifier',1.2),
('def_npc_percent_tyro_rank3','locking_range_modifier',1.1),
('def_npc_percent_tyro_rank3','locking_time_modifier',0.9),
('def_npc_percent_tyro_rank3','missile_cycle_time_modifier',0.9),
('def_npc_percent_tyro_rank3','optimal_range_modifier',1.2),
('def_npc_percent_tyro_rank3','powergrid_max_modifier',2),
('def_npc_percent_tyro_rank3','turret_cycle_time_modifier',0.9),
('def_npc_percent_tyro_rank3','received_repaired_modifier',0.1),
('def_npc_percent_tyro_rank4','armor_max_modifier',1.5),
('def_npc_percent_tyro_rank4','core_max_modifier',1.3),
('def_npc_percent_tyro_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_tyro_rank4','cpu_max_modifier',2),
('def_npc_percent_tyro_rank4','damage_modifier',1.3),
('def_npc_percent_tyro_rank4','falloff_modifier',1.3),
('def_npc_percent_tyro_rank4','locking_range_modifier',1.1),
('def_npc_percent_tyro_rank4','locking_time_modifier',0.9),
('def_npc_percent_tyro_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_tyro_rank4','optimal_range_modifier',1.3),
('def_npc_percent_tyro_rank4','powergrid_max_modifier',2),
('def_npc_percent_tyro_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_tyro_rank4','received_repaired_modifier',0.1),
('def_npc_percent_tyro_rank5','armor_max_modifier',1.7),
('def_npc_percent_tyro_rank5','core_max_modifier',1.5),
('def_npc_percent_tyro_rank5','core_recharge_time_modifier',0.7),
('def_npc_percent_tyro_rank5','cpu_max_modifier',2),
('def_npc_percent_tyro_rank5','damage_modifier',1.5),
('def_npc_percent_tyro_rank5','falloff_modifier',1.3),
('def_npc_percent_tyro_rank5','locking_range_modifier',1.5),
('def_npc_percent_tyro_rank5','locking_time_modifier',0.7),
('def_npc_percent_tyro_rank5','missile_cycle_time_modifier',0.7),
('def_npc_percent_tyro_rank5','optimal_range_modifier',1.3),
('def_npc_percent_tyro_rank5','powergrid_max_modifier',2),
('def_npc_percent_tyro_rank5','turret_cycle_time_modifier',0.7),
('def_npc_percent_tyro_rank5','received_repaired_modifier',0.1),
('def_npc_percent_gropho_rank5','armor_max_modifier',1.7),
('def_npc_percent_gropho_rank5','core_max_modifier',1.5),
('def_npc_percent_gropho_rank5','core_recharge_time_modifier',0.7),
('def_npc_percent_gropho_rank5','cpu_max_modifier',2),
('def_npc_percent_gropho_rank5','damage_modifier',1.5),
('def_npc_percent_gropho_rank5','falloff_modifier',1.3),
('def_npc_percent_gropho_rank5','locking_range_modifier',1.5),
('def_npc_percent_gropho_rank5','locking_time_modifier',0.7),
('def_npc_percent_gropho_rank5','missile_cycle_time_modifier',0.7),
('def_npc_percent_gropho_rank5','optimal_range_modifier',1.3),
('def_npc_percent_gropho_rank5','powergrid_max_modifier',2),
('def_npc_percent_gropho_rank5','turret_cycle_time_modifier',0.7),
('def_npc_percent_gropho_rank5','received_repaired_modifier',0.1),
('def_npc_percent_gropho_rank4','armor_max_modifier',1.5),
('def_npc_percent_gropho_rank4','core_max_modifier',1.3),
('def_npc_percent_gropho_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_gropho_rank4','cpu_max_modifier',2),
('def_npc_percent_gropho_rank4','damage_modifier',1.3),
('def_npc_percent_gropho_rank4','falloff_modifier',1.3),
('def_npc_percent_gropho_rank4','locking_range_modifier',1.1),
('def_npc_percent_gropho_rank4','locking_time_modifier',0.9),
('def_npc_percent_gropho_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_gropho_rank4','optimal_range_modifier',1.3),
('def_npc_percent_gropho_rank4','powergrid_max_modifier',2),
('def_npc_percent_gropho_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_gropho_rank4','received_repaired_modifier',0.1),
('def_npc_percent_seth_rank4','armor_max_modifier',1.5),
('def_npc_percent_seth_rank4','core_max_modifier',1.3),
('def_npc_percent_seth_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_seth_rank4','cpu_max_modifier',2),
('def_npc_percent_seth_rank4','damage_modifier',1.3),
('def_npc_percent_seth_rank4','falloff_modifier',1.3),
('def_npc_percent_seth_rank4','locking_range_modifier',1.1),
('def_npc_percent_seth_rank4','locking_time_modifier',0.9),
('def_npc_percent_seth_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_seth_rank4','optimal_range_modifier',1.3),
('def_npc_percent_seth_rank4','powergrid_max_modifier',2),
('def_npc_percent_seth_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_seth_rank4','received_repaired_modifier',0.1),
('def_npc_percent_seth_rank5','armor_max_modifier',1.7),
('def_npc_percent_seth_rank5','core_max_modifier',1.5),
('def_npc_percent_seth_rank5','core_recharge_time_modifier',0.7),
('def_npc_percent_seth_rank5','cpu_max_modifier',2),
('def_npc_percent_seth_rank5','damage_modifier',1.5),
('def_npc_percent_seth_rank5','falloff_modifier',1.3),
('def_npc_percent_seth_rank5','locking_range_modifier',1.5),
('def_npc_percent_seth_rank5','locking_time_modifier',0.7),
('def_npc_percent_seth_rank5','missile_cycle_time_modifier',0.7),
('def_npc_percent_seth_rank5','optimal_range_modifier',1.3),
('def_npc_percent_seth_rank5','powergrid_max_modifier',2),
('def_npc_percent_seth_rank5','turret_cycle_time_modifier',0.7),
('def_npc_percent_seth_rank5','received_repaired_modifier',0.1),
('def_npc_percent_mesmer_rank5','armor_max_modifier',1.7),
('def_npc_percent_mesmer_rank5','core_max_modifier',1.5),
('def_npc_percent_mesmer_rank5','core_recharge_time_modifier',0.7),
('def_npc_percent_mesmer_rank5','cpu_max_modifier',2),
('def_npc_percent_mesmer_rank5','damage_modifier',1.5),
('def_npc_percent_mesmer_rank5','falloff_modifier',1.3),
('def_npc_percent_mesmer_rank5','locking_range_modifier',1.5),
('def_npc_percent_mesmer_rank5','locking_time_modifier',0.7),
('def_npc_percent_mesmer_rank5','missile_cycle_time_modifier',0.7),
('def_npc_percent_mesmer_rank5','optimal_range_modifier',1.3),
('def_npc_percent_mesmer_rank5','powergrid_max_modifier',2),
('def_npc_percent_mesmer_rank5','turret_cycle_time_modifier',0.7),
('def_npc_percent_mesmer_rank5','received_repaired_modifier',0.1),
('def_npc_percent_mesmer_rank4','armor_max_modifier',1.5),
('def_npc_percent_mesmer_rank4','core_max_modifier',1.3),
('def_npc_percent_mesmer_rank4','core_recharge_time_modifier',0.7),
('def_npc_percent_mesmer_rank4','cpu_max_modifier',2),
('def_npc_percent_mesmer_rank4','damage_modifier',1.3),
('def_npc_percent_mesmer_rank4','falloff_modifier',1.3),
('def_npc_percent_mesmer_rank4','locking_range_modifier',1.1),
('def_npc_percent_mesmer_rank4','locking_time_modifier',0.9),
('def_npc_percent_mesmer_rank4','missile_cycle_time_modifier',0.8),
('def_npc_percent_mesmer_rank4','optimal_range_modifier',1.3),
('def_npc_percent_mesmer_rank4','powergrid_max_modifier',2),
('def_npc_percent_mesmer_rank4','turret_cycle_time_modifier',0.8),
('def_npc_percent_mesmer_rank4','received_repaired_modifier',0.1);


PRINT N'DELETE robottemplates, robottemplaterelation, entitydefaults IF exists (should be 0 for live patch)';
DECLARE @templatesToDelete TABLE (templateid int);
INSERT INTO @templatesToDelete (templateid)
SELECT templateid FROM robottemplaterelation WHERE definition IN (SELECT definition FROM entitydefaults WHERE definitionname IN (SELECT defName FROM #NPCDEFS));

DELETE FROM robottemplaterelation WHERE templateid IN (SELECT templateid FROM @templatesToDelete);
DELETE FROM robottemplates WHERE id IN (SELECT templateid FROM @templatesToDelete);

PRINT N'INSERT/UPDATE (merge) entitydefaults FOR NPCS';
MERGE INTO
  entitydefaults d
USING
  #NPCDEFS n
ON
  n.defName = d.definitionname
WHEN MATCHED THEN
  UPDATE SET
		quantity = 1,
		attributeflags = 1024,
		categoryflags = 911,
		options = '',
		note = '',
		enabled = 1,
		volume = 0,
		mass = 0,
		hidden = 0,
		health = 100,
		descriptiontoken = n.defName+'_desc',
		purchasable = 0,
		tierlevel = 0,
		tiertype = 0
WHEN NOT MATCHED THEN
	INSERT (definitionname,quantity,attributeflags,categoryflags,options,note,enabled,volume,mass,hidden,health,descriptiontoken,purchasable,tiertype,tierlevel)
	VALUES (defName, 1, 1024, 911, '', '', 1, 0, 0, 0, 100, defName+'_desc', 0, 0, 0);


PRINT N'INSERT robottemplates FOR NPCS';
INSERT INTO robottemplates (name, description, note)
SELECT defName+'_template', template, 'new ore npcs template for '+defName FROM #NPCDEFS;

PRINT N'INSERT robottemplaterelation FOR NPCS';
INSERT INTO robottemplaterelation (definition, templateid, itemscoresum, raceid, missionlevel, missionleveloverride, killep, note)
SELECT (SELECT definition FROM entitydefaults WHERE definitionname=defName),
	(SELECT id FROM robottemplates WHERE name = defName+'_template'),
	0, 0, NULL, NULL, ep, 'template relation for '+defName
FROM #NPCDEFS;


PRINT N'DELETE OLD STATS';
DELETE FROM aggregatevalues WHERE definition in (SELECT definition FROM entitydefaults WHERE definitionname in (SELECT DISTINCT defName FROM #NPCMODS));

PRINT N'INSERT NEW STATS';
INSERT INTO [dbo].[aggregatevalues] ([definition],[field],[value])
SELECT 
	(SELECT TOP 1 definition FROM entitydefaults WHERE defName=definitionname),
	(SELECT TOP 1 id FROM aggregatefields WHERE fieldName=name),
	fieldValue 
FROM #NPCMODS

GO