USE [perpetuumsa]
GO

---------------------------------------------
-- GAMMA ARTIFACT SPAWN INFO
--
-- Date Modified: 2021/08/01
---------------------------------------------


DROP TABLE IF EXISTS #GAMMA_ARTI_SPAWN_INFO;
CREATE TABLE #GAMMA_ARTI_SPAWN_INFO(
	tier INT NULL,
	artifactTypeName VARCHAR(100),
	probWeight FLOAT
);
INSERT INTO #GAMMA_ARTI_SPAWN_INFO(tier, artifactTypeName, probWeight) VALUES
--(0,'salvage_pelistal_level1_gamma',0),
--(0,'observer_pelistal_level1_gamma',0),
--(0,'infestation_pelistal_level1_gamma',0),
--(0,'industrial_pelistal_level1_gamma',0),
(0,'salvage_pelistal_level2_gamma',10),
(0,'science_pelistal_level2_gamma',10),
(0,'observer_pelistal_level2_gamma',10),
(0,'infestation_pelistal_level2_gamma',10),
(0,'industrial_pelistal_level2_gamma',10),
(0,'salvage_pelistal_level3_gamma',75),
(0,'science_pelistal_level3_gamma',75),
(0,'observer_pelistal_level3_gamma',75),
(0,'infestation_pelistal_level3_gamma',75),
(0,'industrial_pelistal_level3_gamma',75),
--(0,'science_nuimqol_level1_gamma',0),
--(0,'salvage_nuimqol_level1_gamma',0),
--(0,'observer_nuimqol_level1_gamma',0),
--(0,'infestation_nuimqol_level1_gamma',0),
--(0,'industrial_nuimqol_level1_gamma',0),
(0,'salvage_nuimqol_level2_gamma',10),
(0,'science_nuimqol_level2_gamma',10),
(0,'observer_nuimqol_level2_gamma',10),
(0,'infestation_nuimqol_level2_gamma',10),
(0,'industrial_nuimqol_level2_gamma',10),
(0,'salvage_nuimqol_level3_gamma',75),
(0,'science_nuimqol_level3_gamma',75),
(0,'observer_nuimqol_level3_gamma',75),
(0,'infestation_nuimqol_level3_gamma',75),
(0,'industrial_nuimqol_level3_gamma',75),
--(0,'salvage_thelodica_level1_gamma',0),
--(0,'science_thelodica_level1_gamma',0),
--(0,'observer_thelodica_level1_gamma',0),
--(0,'infestation_thelodica_level1_gamma',0),
--(0,'industrial_thelodica_level1_gamma',0),
(0,'salvage_thelodica_level2_gamma',10),
(0,'infestation_thelodica_level2_gamma',10),
(0,'industrial_thelodica_level2_gamma',10),
(0,'salvage_thelodica_level3_gamma',75),
(0,'science_thelodica_level3_gamma',75),
(0,'observer_thelodica_level3_gamma',75),
(0,'infestation_thelodica_level3_gamma',75),
(0,'industrial_thelodica_level3_gamma',75),

--(1,'salvage_pelistal_level1_gamma',0),
--(1,'observer_pelistal_level1_gamma',0),
--(1,'infestation_pelistal_level1_gamma',0),
--(1,'industrial_pelistal_level1_gamma',0),
(1,'salvage_pelistal_level2_gamma',25),
(1,'science_pelistal_level2_gamma',25),
(1,'observer_pelistal_level2_gamma',25),
(1,'infestation_pelistal_level2_gamma',25),
(1,'industrial_pelistal_level2_gamma',25),
(1,'salvage_pelistal_level3_gamma',50),
(1,'science_pelistal_level3_gamma',50),
(1,'observer_pelistal_level3_gamma',50),
(1,'infestation_pelistal_level3_gamma',50),
(1,'industrial_pelistal_level3_gamma',50),
--(1,'science_nuimqol_level1_gamma',0),
--(1,'salvage_nuimqol_level1_gamma',0),
--(1,'observer_nuimqol_level1_gamma',0),
--(1,'infestation_nuimqol_level1_gamma',0),
--(1,'industrial_nuimqol_level1_gamma',0),
(1,'salvage_nuimqol_level2_gamma',25),
(1,'science_nuimqol_level2_gamma',25),
(1,'observer_nuimqol_level2_gamma',25),
(1,'infestation_nuimqol_level2_gamma',25),
(1,'industrial_nuimqol_level2_gamma',25),
(1,'salvage_nuimqol_level3_gamma',50),
(1,'science_nuimqol_level3_gamma',50),
(1,'observer_nuimqol_level3_gamma',50),
(1,'infestation_nuimqol_level3_gamma',50),
(1,'industrial_nuimqol_level3_gamma',50),
--(1,'salvage_thelodica_level1_gamma',0),
--(1,'science_thelodica_level1_gamma',0),
--(1,'observer_thelodica_level1_gamma',0),
--(1,'infestation_thelodica_level1_gamma',0),
--(1,'industrial_thelodica_level1_gamma',0),
(1,'salvage_thelodica_level2_gamma',25),
(1,'infestation_thelodica_level2_gamma',25),
(1,'industrial_thelodica_level2_gamma',25),
(1,'salvage_thelodica_level3_gamma',50),
(1,'science_thelodica_level3_gamma',50),
(1,'observer_thelodica_level3_gamma',50),
(1,'infestation_thelodica_level3_gamma',50),
(1,'industrial_thelodica_level3_gamma',50),

(2,'salvage_pelistal_level1_gamma',5),
(2,'observer_pelistal_level1_gamma',5),
(2,'infestation_pelistal_level1_gamma',5),
(2,'industrial_pelistal_level1_gamma',5),
(2,'salvage_pelistal_level2_gamma',20),
(2,'science_pelistal_level2_gamma',20),
(2,'observer_pelistal_level2_gamma',20),
(2,'infestation_pelistal_level2_gamma',20),
(2,'industrial_pelistal_level2_gamma',20),
(2,'salvage_pelistal_level3_gamma',50),
(2,'science_pelistal_level3_gamma',50),
(2,'observer_pelistal_level3_gamma',50),
(2,'infestation_pelistal_level3_gamma',50),
(2,'industrial_pelistal_level3_gamma',50),
(2,'science_nuimqol_level1_gamma',5),
(2,'salvage_nuimqol_level1_gamma',5),
(2,'observer_nuimqol_level1_gamma',5),
(2,'infestation_nuimqol_level1_gamma',5),
(2,'industrial_nuimqol_level1_gamma',5),
(2,'salvage_nuimqol_level2_gamma',20),
(2,'science_nuimqol_level2_gamma',20),
(2,'observer_nuimqol_level2_gamma',20),
(2,'infestation_nuimqol_level2_gamma',20),
(2,'industrial_nuimqol_level2_gamma',20),
(2,'salvage_nuimqol_level3_gamma',50),
(2,'science_nuimqol_level3_gamma',50),
(2,'observer_nuimqol_level3_gamma',50),
(2,'infestation_nuimqol_level3_gamma',50),
(2,'industrial_nuimqol_level3_gamma',50),
(2,'salvage_thelodica_level1_gamma',5),
(2,'science_thelodica_level1_gamma',5),
(2,'observer_thelodica_level1_gamma',5),
(2,'infestation_thelodica_level1_gamma',5),
(2,'industrial_thelodica_level1_gamma',5),
(2,'salvage_thelodica_level2_gamma',20),
(2,'infestation_thelodica_level2_gamma',20),
(2,'industrial_thelodica_level2_gamma',20),
(2,'salvage_thelodica_level3_gamma',50),
(2,'science_thelodica_level3_gamma',50),
(2,'observer_thelodica_level3_gamma',50),
(2,'infestation_thelodica_level3_gamma',50),
(2,'industrial_thelodica_level3_gamma',50),

(3,'salvage_pelistal_level1_gamma',10),
(3,'observer_pelistal_level1_gamma',10),
(3,'infestation_pelistal_level1_gamma',10),
(3,'industrial_pelistal_level1_gamma',10),
(3,'salvage_pelistal_level2_gamma',15),
(3,'science_pelistal_level2_gamma',15),
(3,'observer_pelistal_level2_gamma',15),
(3,'infestation_pelistal_level2_gamma',15),
(3,'industrial_pelistal_level2_gamma',15),
(3,'salvage_pelistal_level3_gamma',20),
(3,'science_pelistal_level3_gamma',20),
(3,'observer_pelistal_level3_gamma',20),
(3,'infestation_pelistal_level3_gamma',20),
(3,'industrial_pelistal_level3_gamma',20),
(3,'science_nuimqol_level1_gamma',10),
(3,'salvage_nuimqol_level1_gamma',10),
(3,'observer_nuimqol_level1_gamma',10),
(3,'infestation_nuimqol_level1_gamma',10),
(3,'industrial_nuimqol_level1_gamma',10),
(3,'salvage_nuimqol_level2_gamma',15),
(3,'science_nuimqol_level2_gamma',15),
(3,'observer_nuimqol_level2_gamma',15),
(3,'infestation_nuimqol_level2_gamma',15),
(3,'industrial_nuimqol_level2_gamma',15),
(3,'salvage_nuimqol_level3_gamma',20),
(3,'science_nuimqol_level3_gamma',20),
(3,'observer_nuimqol_level3_gamma',20),
(3,'infestation_nuimqol_level3_gamma',20),
(3,'industrial_nuimqol_level3_gamma',20),
(3,'salvage_thelodica_level1_gamma',10),
(3,'science_thelodica_level1_gamma',10),
(3,'observer_thelodica_level1_gamma',10),
(3,'infestation_thelodica_level1_gamma',10),
(3,'industrial_thelodica_level1_gamma',10),
(3,'salvage_thelodica_level2_gamma',15),
(3,'infestation_thelodica_level2_gamma',15),
(3,'industrial_thelodica_level2_gamma',15),
(3,'salvage_thelodica_level3_gamma',20),
(3,'science_thelodica_level3_gamma',20),
(3,'observer_thelodica_level3_gamma',20),
(3,'infestation_thelodica_level3_gamma',20),
(3,'industrial_thelodica_level3_gamma',20);

SELECT * FROM artifactspawninfo WHERE zoneid > 99 AND zoneid < 141;
DELETE artifactspawninfo WHERE zoneid > 99 AND zoneid < 141;

INSERT INTO artifactspawninfo(artifacttype, zoneid, rate)
SELECT 
	(SELECT TOP 1 id FROM artifacttypes WHERE i.artifactTypeName=name),
	z.id,
	i.probWeight
FROM #GAMMA_ARTI_SPAWN_INFO i
JOIN zones z ON z.pbsTechLimit=i.tier AND z.id > 105
ORDER BY z.pbsTechLimit, z.id;


DROP TABLE IF EXISTS #GAMMA_ARTI_SPAWN_INFO;
GO