USE [perpetuumsa]
GO

----------------------------------------------
-- Gamma NPC loots part 2: the bespoke ones
-- indy/courier/observer/mini/boss
-- Date modified: 2021/11/04
----------------------------------------------


DROP TABLE IF EXISTS #LOOTS;
CREATE TABLE #LOOTS(
	defName VARCHAR(128),
	lootName VARCHAR(128),
	minQuant INT,
	maxQuant INT,
	prob FLOAT
);
INSERT INTO #LOOTS (defName, lootName, minQuant, maxQuant, prob) VALUES
('def_npc_gamma_sequer_basic_lindy','def_kernel_industrial',6656,9984,1),
('def_npc_gamma_sequer_basic_lindy','def_kernel_common',3328,6656,1),
('def_npc_gamma_sequer_basic_lindy','def_kernel_hitech',1664,2496,1),
('def_npc_gamma_sequer_basic_lindy','def_common_reactor_plasma',3000,3600,1),
('def_npc_gamma_sequer_basic_lindy','def_robotshard_common_basic',8,84,0.5),
('def_npc_gamma_sequer_basic_lindy','def_robotshard_common_advanced',6,60,0.5),
('def_npc_gamma_sequer_basic_lindy','def_robotshard_common_expert',4,36,0.5),
('def_npc_gamma_sequer_basic_lindy','def_named3_shield_hardener',1,1,0.06),
('def_npc_gamma_sequer_basic_lindy','def_named3_small_shield_generator',1,1,0.06),
('def_npc_gamma_sequer_basic_lindy','def_named3_small_core_battery',1,1,0.06),
('def_npc_gamma_sequer_basic_lindy','def_named2_shield_hardener',1,1,0.088),
('def_npc_gamma_sequer_basic_lindy','def_named2_small_shield_generator',1,1,0.088),
('def_npc_gamma_sequer_basic_lindy','def_named2_small_core_battery',1,1,0.088),
('def_npc_gamma_sequer_basic_lindy','def_named1_shield_hardener',1,1,0.126),
('def_npc_gamma_sequer_basic_lindy','def_named1_small_shield_generator',1,1,0.126),
('def_npc_gamma_sequer_basic_lindy','def_named1_small_core_battery',1,1,0.126),
('def_npc_gamma_sequer_basic_lindy','def_standard_shield_hardener',1,1,0.25),
('def_npc_gamma_sequer_basic_lindy','def_standard_small_shield_generator',1,1,0.25),
('def_npc_gamma_sequer_basic_lindy','def_standard_small_core_battery',1,1,0.25),
('def_npc_gamma_sequer_basic_lindy','def_container_capsule',1,1,0.5),
('def_npc_gamma_sequer_basic_lindy','def_npc_egg_industrial_small_expert_capsule',1,1,0.3),
('def_npc_gamma_sequer_basic_lindy','def_npc_egg_industrial_small_miniboss3_capsule',1,1,0.1),
('def_npc_gamma_sequer_basic_lindy','def_epriton',5000,50000,0.15),
('def_npc_gamma_sequer_basic_lindy','def_stermonit',10000,100000,0.35),
('def_npc_gamma_sequer_basic_lindy','def_imentium',10000,100000,0.35),
('def_npc_gamma_sequer_basic_lindy','def_silgium',10000,100000,0.35),
('def_npc_gamma_sequer_basic_lindy','def_electroplant_fruit',2500,25000,0.15),
('def_npc_gamma_sequer_basic_lindy','def_helioptris',5000,50000,0.35),
('def_npc_gamma_sequer_basic_lindy','def_triandlus',5000,50000,0.35),
('def_npc_gamma_sequer_basic_lindy','def_prismocitae',5000,50000,0.35),


('def_npc_gamma_lithus_basic_lindy','def_kernel_industrial',16640,24960,1),
('def_npc_gamma_lithus_basic_lindy','def_kernel_common',8320,12480,1),
('def_npc_gamma_lithus_basic_lindy','def_kernel_hitech',1664,2496,1),
('def_npc_gamma_lithus_basic_lindy','def_common_reactor_plasma',9600,12000,1),
('def_npc_gamma_lithus_basic_lindy','def_robotshard_common_basic',12,120,0.5),
('def_npc_gamma_lithus_basic_lindy','def_robotshard_common_advanced',12,120,0.5),
('def_npc_gamma_lithus_basic_lindy','def_robotshard_common_expert',12,120,0.5),
('def_npc_gamma_lithus_basic_lindy','def_named3_shield_hardener',1,1,0.11),
('def_npc_gamma_lithus_basic_lindy','def_named3_medium_shield_generator',1,1,0.11),
('def_npc_gamma_lithus_basic_lindy','def_named3_medium_core_battery',1,1,0.11),
('def_npc_gamma_lithus_basic_lindy','def_named2_shield_hardener',1,1,0.125),
('def_npc_gamma_lithus_basic_lindy','def_named2_medium_shield_generator',1,1,0.125),
('def_npc_gamma_lithus_basic_lindy','def_named2_medium_core_battery',1,1,0.125),
('def_npc_gamma_lithus_basic_lindy','def_named1_shield_hardener',1,1,0.22),
('def_npc_gamma_lithus_basic_lindy','def_named1_medium_shield_generator',1,1,0.22),
('def_npc_gamma_lithus_basic_lindy','def_named1_medium_core_battery',1,1,0.22),
('def_npc_gamma_lithus_basic_lindy','def_standard_shield_hardener',1,1,0.25),
('def_npc_gamma_lithus_basic_lindy','def_standard_medium_shield_generator',1,1,0.25),
('def_npc_gamma_lithus_basic_lindy','def_standard_medium_core_battery',1,1,0.25),
('def_npc_gamma_lithus_basic_lindy','def_container_capsule',1,1,0.7),
('def_npc_gamma_lithus_basic_lindy','def_npc_egg_industrial_medium_advanced_capsule',1,1,0.3),
('def_npc_gamma_lithus_basic_lindy','def_npc_egg_industrial_medium_miniboss2_capsule',1,1,0.1),
('def_npc_gamma_lithus_basic_lindy','def_epriton',30000,300000,0.15),
('def_npc_gamma_lithus_basic_lindy','def_stermonit',100000,500000,0.35),
('def_npc_gamma_lithus_basic_lindy','def_imentium',100000,500000,0.35),
('def_npc_gamma_lithus_basic_lindy','def_silgium',100000,500000,0.35),
('def_npc_gamma_lithus_basic_lindy','def_electroplant_fruit',15000,150000,0.15),
('def_npc_gamma_lithus_basic_lindy','def_helioptris',50000,250000,0.35),
('def_npc_gamma_lithus_basic_lindy','def_triandlus',50000,250000,0.35),
('def_npc_gamma_lithus_basic_lindy','def_prismocitae',50000,250000,0.35),


('def_npc_gamma_scarab_basic_lindy','def_kernel_industrial',24960,49920,1),
('def_npc_gamma_scarab_basic_lindy','def_kernel_common',12480,18720,1),
('def_npc_gamma_scarab_basic_lindy','def_kernel_hitech',2496,3744,1),
('def_npc_gamma_scarab_basic_lindy','def_common_reactor_plasma',14400,18000,1),
('def_npc_gamma_scarab_basic_lindy','def_robotshard_common_basic',14,144,0.5),
('def_npc_gamma_scarab_basic_lindy','def_robotshard_common_advanced',24,240,0.5),
('def_npc_gamma_scarab_basic_lindy','def_robotshard_common_expert',34,336,0.5),
('def_npc_gamma_scarab_basic_lindy','def_named3_shield_hardener',1,1,0.11),
('def_npc_gamma_scarab_basic_lindy','def_named3_medium_shield_generator',1,1,0.11),
('def_npc_gamma_scarab_basic_lindy','def_named3_medium_armor_plate',1,1,0.11),
('def_npc_gamma_scarab_basic_lindy','def_named2_shield_hardener',1,1,0.125),
('def_npc_gamma_scarab_basic_lindy','def_named2_medium_shield_generator',1,1,0.125),
('def_npc_gamma_scarab_basic_lindy','def_named2_medium_armor_plate',1,1,0.125),
('def_npc_gamma_scarab_basic_lindy','def_named1_shield_hardener',1,1,0.22),
('def_npc_gamma_scarab_basic_lindy','def_named1_medium_shield_generator',1,1,0.22),
('def_npc_gamma_scarab_basic_lindy','def_named1_medium_armor_plate',1,1,0.22),
('def_npc_gamma_scarab_basic_lindy','def_standard_shield_hardener',1,1,0.25),
('def_npc_gamma_scarab_basic_lindy','def_standard_medium_shield_generator',1,1,0.25),
('def_npc_gamma_scarab_basic_lindy','def_standard_medium_armor_plate',1,1,0.25),
('def_npc_gamma_scarab_basic_lindy','def_container_capsule',1,1,1),
('def_npc_gamma_scarab_basic_lindy','def_npc_egg_industrial_medium_expert_capsule',1,1,0.5),
('def_npc_gamma_scarab_basic_lindy','def_npc_egg_industrial_medium_miniboss3_capsule',1,1,0.25),
('def_npc_gamma_scarab_basic_lindy','def_epriton',300000,3000000,0.15),
('def_npc_gamma_scarab_basic_lindy','def_stermonit',1000000,5000000,0.35),
('def_npc_gamma_scarab_basic_lindy','def_imentium',1000000,5000000,0.35),
('def_npc_gamma_scarab_basic_lindy','def_silgium',1000000,5000000,0.35),
('def_npc_gamma_scarab_basic_lindy','def_electroplant_fruit',150000,1500000,0.15),
('def_npc_gamma_scarab_basic_lindy','def_helioptris',500000,2500000,0.35),
('def_npc_gamma_scarab_basic_lindy','def_triandlus',500000,2500000,0.35),
('def_npc_gamma_scarab_basic_lindy','def_prismocitae',500000,2500000,0.35),


('def_npc_gamma_ikarus_basic_lindy','def_kernel_industrial',3328,4992,1),
('def_npc_gamma_ikarus_basic_lindy','def_kernel_common',1664,3328,1),
('def_npc_gamma_ikarus_basic_lindy','def_kernel_hitech',832,1248,1),
('def_npc_gamma_ikarus_basic_lindy','def_common_reactor_plasma',1500,1800,1),
('def_npc_gamma_ikarus_basic_lindy','def_robotshard_common_basic',4,36,0.5),
('def_npc_gamma_ikarus_basic_lindy','def_robotshard_common_advanced',2,24,0.5),
('def_npc_gamma_ikarus_basic_lindy','def_robotshard_common_expert',1,12,0.5),
('def_npc_gamma_ikarus_basic_lindy','def_named3_mass_reductor',1,1,0.06),
('def_npc_gamma_ikarus_basic_lindy','def_named2_mass_reductor',1,1,0.088),
('def_npc_gamma_ikarus_basic_lindy','def_named1_mass_reductor',1,1,0.126),
('def_npc_gamma_ikarus_basic_lindy','def_standard_mass_reductor',1,1,0.25),
('def_npc_gamma_ikarus_basic_lindy','def_container_capsule',1,1,0.45),
('def_npc_gamma_ikarus_basic_lindy','def_stermonit',5000,50000,0.35),
('def_npc_gamma_ikarus_basic_lindy','def_imentium',5000,50000,0.35),
('def_npc_gamma_ikarus_basic_lindy','def_silgium',5000,50000,0.35),
('def_npc_gamma_ikarus_basic_lindy','def_biotichrin',300,3000,0.1),


('def_npc_gamma_daidalos_basic_lindy','def_kernel_industrial',12480,18720,1),
('def_npc_gamma_daidalos_basic_lindy','def_kernel_common',6240,9360,1),
('def_npc_gamma_daidalos_basic_lindy','def_kernel_hitech',1248,1872,1),
('def_npc_gamma_daidalos_basic_lindy','def_common_reactor_plasma',7200,9000,1),
('def_npc_gamma_daidalos_basic_lindy','def_robotshard_common_basic',1,12,0.5),
('def_npc_gamma_daidalos_basic_lindy','def_robotshard_common_advanced',4,36,0.5),
('def_npc_gamma_daidalos_basic_lindy','def_robotshard_common_expert',6,60,0.5),
('def_npc_gamma_daidalos_basic_lindy','def_ammo_medium_projectile_d',100,200,0.5),
('def_npc_gamma_daidalos_basic_lindy','def_named3_longrange_medium_autocannon',1,1,0.11),
('def_npc_gamma_daidalos_basic_lindy','def_named3_damage_mod_projectile',1,1,0.11),
('def_npc_gamma_daidalos_basic_lindy','def_named3_medium_armor_plate',1,1,0.11),
('def_npc_gamma_daidalos_basic_lindy','def_named3_medium_armor_repairer',1,1,0.11),
('def_npc_gamma_daidalos_basic_lindy','def_named2_longrange_medium_autocannon',1,1,0.125),
('def_npc_gamma_daidalos_basic_lindy','def_named2_damage_mod_projectile',1,1,0.125),
('def_npc_gamma_daidalos_basic_lindy','def_named2_medium_armor_plate',1,1,0.125),
('def_npc_gamma_daidalos_basic_lindy','def_named2_medium_armor_repairer',1,1,0.125),
('def_npc_gamma_daidalos_basic_lindy','def_named1_longrange_medium_autocannon',1,1,0.22),
('def_npc_gamma_daidalos_basic_lindy','def_named1_damage_mod_projectile',1,1,0.22),
('def_npc_gamma_daidalos_basic_lindy','def_named1_medium_armor_plate',1,1,0.22),
('def_npc_gamma_daidalos_basic_lindy','def_named1_medium_armor_repairer',1,1,0.22),
('def_npc_gamma_daidalos_basic_lindy','def_longrange_standard_medium_autocannon',1,1,0.25),
('def_npc_gamma_daidalos_basic_lindy','def_standard_damage_mod_projectile',1,1,0.25),
('def_npc_gamma_daidalos_basic_lindy','def_standard_medium_armor_plate',1,1,0.25),
('def_npc_gamma_daidalos_basic_lindy','def_standard_medium_armor_repairer',1,1,0.25),
('def_npc_gamma_daidalos_basic_lindy','def_container_capsule',1,1,0.7),
('def_npc_gamma_daidalos_basic_lindy','def_stermonit',5000,250000,0.35),
('def_npc_gamma_daidalos_basic_lindy','def_imentium',5000,250000,0.35),
('def_npc_gamma_daidalos_basic_lindy','def_silgium',5000,250000,0.35),
('def_npc_gamma_daidalos_basic_lindy','def_biotichrin',1200,12000,0.1),


('def_npc_gamma_cronus_basic_lindy','def_kernel_industrial',6656,9984,1),
('def_npc_gamma_cronus_basic_lindy','def_kernel_common',4160,6240,1),
('def_npc_gamma_cronus_basic_lindy','def_kernel_hitech',1664,2496,1),
('def_npc_gamma_cronus_basic_lindy','def_common_reactor_plasma',1416,1776,1),
('def_npc_gamma_cronus_basic_lindy','def_robotshard_common_basic',6,60,0.5),
('def_npc_gamma_cronus_basic_lindy','def_robotshard_common_advanced',6,60,0.5),
('def_npc_gamma_cronus_basic_lindy','def_robotshard_common_expert',6,60,0.5),
('def_npc_gamma_cronus_basic_lindy','def_plant_bomb_capsule',1,1,0.1),
('def_npc_gamma_cronus_basic_lindy','def_named3_mining_upgrade',1,1,0.06),
('def_npc_gamma_cronus_basic_lindy','def_named3_small_shield_generator',1,1,0.06),
('def_npc_gamma_cronus_basic_lindy','def_named3_small_driller',1,1,0.03),
('def_npc_gamma_cronus_basic_lindy','def_named3_small_harvester',1,1,0.03),
('def_npc_gamma_cronus_basic_lindy','def_named1_medium_driller',1,1,0.03),
('def_npc_gamma_cronus_basic_lindy','def_named1_medium_harvester',1,1,0.03),
('def_npc_gamma_cronus_basic_lindy','def_named2_mining_upgrade',1,1,0.088),
('def_npc_gamma_cronus_basic_lindy','def_named2_small_shield_generator',1,1,0.088),
('def_npc_gamma_cronus_basic_lindy','def_named2_small_driller',1,1,0.044),
('def_npc_gamma_cronus_basic_lindy','def_named2_small_harvester',1,1,0.044),
('def_npc_gamma_cronus_basic_lindy','def_named1_mining_upgrade',1,1,0.126),
('def_npc_gamma_cronus_basic_lindy','def_named1_small_shield_generator',1,1,0.126),
('def_npc_gamma_cronus_basic_lindy','def_named1_small_driller',1,1,0.063),
('def_npc_gamma_cronus_basic_lindy','def_named1_small_harvester',1,1,0.0315),
('def_npc_gamma_cronus_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_cronus_basic_lindy','def_standard_small_shield_generator',1,1,0.25),
('def_npc_gamma_cronus_basic_lindy','def_standard_small_driller',1,1,0.125),
('def_npc_gamma_cronus_basic_lindy','def_standard_small_harvester',1,1,0.125),
('def_npc_gamma_cronus_basic_lindy','def_standard_medium_driller',1,1,0.125),
('def_npc_gamma_cronus_basic_lindy','def_standard_medium_harvester',1,1,0.125),
('def_npc_gamma_cronus_basic_lindy','def_ammo_mining_imentium',25,125,0.25),
('def_npc_gamma_cronus_basic_lindy','def_ammo_mining_stermonit',25,125,0.25),
('def_npc_gamma_cronus_basic_lindy','def_ammo_mining_silgium',25,125,0.25),
('def_npc_gamma_cronus_basic_lindy','def_ammo_harvesting_standard',50,250,0.25),


('def_npc_gamma_riveler_basic_lindy','def_kernel_industrial',16640,24960,1),
('def_npc_gamma_riveler_basic_lindy','def_kernel_common',8320,12480,1),
('def_npc_gamma_riveler_basic_lindy','def_kernel_hitech',1664,2496,1),
('def_npc_gamma_riveler_basic_lindy','def_common_reactor_plasma',9600,12000,1),
('def_npc_gamma_riveler_basic_lindy','def_robotshard_common_basic',6,60,0.5),
('def_npc_gamma_riveler_basic_lindy','def_robotshard_common_advanced',12,120,0.5),
('def_npc_gamma_riveler_basic_lindy','def_robotshard_common_expert',18,180,0.5),
('def_npc_gamma_riveler_basic_lindy','def_named3_mining_upgrade',1,1,0.11),
('def_npc_gamma_riveler_basic_lindy','def_named3_medium_shield_generator',1,1,0.11),
('def_npc_gamma_riveler_basic_lindy','def_named3_medium_driller',1,2,0.11),
('def_npc_gamma_riveler_basic_lindy','def_named3_mining_probe_module',1,1,0.11),
('def_npc_gamma_riveler_basic_lindy','def_named3_core_recharger',1,1,0.11),
('def_npc_gamma_riveler_basic_lindy','def_named2_mining_upgrade',1,1,0.125),
('def_npc_gamma_riveler_basic_lindy','def_named2_medium_shield_generator',1,1,0.125),
('def_npc_gamma_riveler_basic_lindy','def_named2_medium_driller',1,2,0.125),
('def_npc_gamma_riveler_basic_lindy','def_named2_mining_probe_module',1,1,0.125),
('def_npc_gamma_riveler_basic_lindy','def_named2_core_recharger',1,1,0.125),
('def_npc_gamma_riveler_basic_lindy','def_named1_mining_upgrade',1,1,0.22),
('def_npc_gamma_riveler_basic_lindy','def_named1_medium_shield_generator',1,1,0.22),
('def_npc_gamma_riveler_basic_lindy','def_named1_medium_driller',1,2,0.22),
('def_npc_gamma_riveler_basic_lindy','def_named1_mining_probe_module',1,1,0.22),
('def_npc_gamma_riveler_basic_lindy','def_named1_core_recharger',1,1,0.22),
('def_npc_gamma_riveler_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_riveler_basic_lindy','def_standard_medium_shield_generator',1,1,0.25),
('def_npc_gamma_riveler_basic_lindy','def_standard_medium_driller',1,2,0.25),
('def_npc_gamma_riveler_basic_lindy','def_standard_mining_probe_module',1,1,0.25),
('def_npc_gamma_riveler_basic_lindy','def_standard_core_recharger',1,1,0.25),
('def_npc_gamma_riveler_basic_lindy','def_ammo_mining_imentium',100,2000,0.5),
('def_npc_gamma_riveler_basic_lindy','def_ammo_mining_stermonit',100,2000,0.5),
('def_npc_gamma_riveler_basic_lindy','def_ammo_mining_epriton',100,2000,0.1),
('def_npc_gamma_riveler_basic_lindy','def_ammo_mining_silgium',100,2000,0.5),
('def_npc_gamma_riveler_basic_lindy','def_ammo_mining_fluxore',100,2000,0.1),


('def_npc_gamma_symbiont_basic_lindy','def_kernel_industrial',16640,24960,1),
('def_npc_gamma_symbiont_basic_lindy','def_kernel_common',8320,12480,1),
('def_npc_gamma_symbiont_basic_lindy','def_kernel_hitech',1664,2496,1),
('def_npc_gamma_symbiont_basic_lindy','def_common_reactor_plasma',9600,12000,1),
('def_npc_gamma_symbiont_basic_lindy','def_robotshard_common_basic',6,60,0.5),
('def_npc_gamma_symbiont_basic_lindy','def_robotshard_common_advanced',12,120,0.5),
('def_npc_gamma_symbiont_basic_lindy','def_robotshard_common_expert',18,180,0.5),
('def_npc_gamma_symbiont_basic_lindy','def_named3_mining_upgrade',1,1,0.11),
('def_npc_gamma_symbiont_basic_lindy','def_named3_medium_shield_generator',1,1,0.11),
('def_npc_gamma_symbiont_basic_lindy','def_named3_medium_harvester',1,2,0.11),
('def_npc_gamma_symbiont_basic_lindy','def_named3_stealth_modul',1,1,0.11),
('def_npc_gamma_symbiont_basic_lindy','def_named3_core_recharger',1,1,0.11),
('def_npc_gamma_symbiont_basic_lindy','def_named2_mining_upgrade',1,1,0.125),
('def_npc_gamma_symbiont_basic_lindy','def_named2_medium_shield_generator',1,1,0.125),
('def_npc_gamma_symbiont_basic_lindy','def_named2_medium_harvester',1,2,0.125),
('def_npc_gamma_symbiont_basic_lindy','def_named2_stealth_modul',1,1,0.125),
('def_npc_gamma_symbiont_basic_lindy','def_named2_core_recharger',1,1,0.125),
('def_npc_gamma_symbiont_basic_lindy','def_named1_mining_upgrade',1,1,0.22),
('def_npc_gamma_symbiont_basic_lindy','def_named1_medium_shield_generator',1,1,0.22),
('def_npc_gamma_symbiont_basic_lindy','def_named1_medium_harvester',1,2,0.22),
('def_npc_gamma_symbiont_basic_lindy','def_named1_stealth_modul',1,1,0.22),
('def_npc_gamma_symbiont_basic_lindy','def_named1_core_recharger',1,1,0.22),
('def_npc_gamma_symbiont_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_symbiont_basic_lindy','def_standard_medium_shield_generator',1,1,0.25),
('def_npc_gamma_symbiont_basic_lindy','def_standard_medium_harvester',1,2,0.25),
('def_npc_gamma_symbiont_basic_lindy','def_standard_stealth_modul',1,1,0.25),
('def_npc_gamma_symbiont_basic_lindy','def_standard_core_recharger',1,1,0.25),
('def_npc_gamma_symbiont_basic_lindy','def_ammo_harvesting_standard',100,2500,1),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_electroplant',10,20,0.6),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_titanplant',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_bonsai',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_poffeteg',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_irontree',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_quag',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_pinetree',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_rango',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_rustbush',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_slimeroot',10,20,0.2),
('def_npc_gamma_symbiont_basic_lindy','def_plant_seed_coppertree',10,20,0.2),


('def_npc_gamma_termis_basic_lindy','def_kernel_industrial',13312,19968,1),
('def_npc_gamma_termis_basic_lindy','def_kernel_common',8320,12480,1),
('def_npc_gamma_termis_basic_lindy','def_kernel_hitech',3328,4992,1),
('def_npc_gamma_termis_basic_lindy','def_common_reactor_plasma',2832,3552,1),
('def_npc_gamma_termis_basic_lindy','def_robotshard_common_basic',7,72,0.5),
('def_npc_gamma_termis_basic_lindy','def_robotshard_common_advanced',7,72,0.5),
('def_npc_gamma_termis_basic_lindy','def_robotshard_common_expert',7,72,0.5),
('def_npc_gamma_termis_basic_lindy','def_named3_mining_upgrade',1,1,0.0825),
('def_npc_gamma_termis_basic_lindy','def_named3_medium_shield_generator',1,1,0.0825),
('def_npc_gamma_termis_basic_lindy','def_named3_medium_driller',1,2,0.0825),
('def_npc_gamma_termis_basic_lindy','def_named3_mining_probe_module',1,1,0.0825),
('def_npc_gamma_termis_basic_lindy','def_named3_core_recharger',1,1,0.0825),
('def_npc_gamma_termis_basic_lindy','def_named2_mining_upgrade',1,1,0.09375),
('def_npc_gamma_termis_basic_lindy','def_named2_medium_shield_generator',1,1,0.09375),
('def_npc_gamma_termis_basic_lindy','def_named2_medium_driller',1,2,0.09375),
('def_npc_gamma_termis_basic_lindy','def_named2_mining_probe_module',1,1,0.09375),
('def_npc_gamma_termis_basic_lindy','def_named2_core_recharger',1,1,0.09375),
('def_npc_gamma_termis_basic_lindy','def_named1_mining_upgrade',1,1,0.165),
('def_npc_gamma_termis_basic_lindy','def_named1_medium_shield_generator',1,1,0.165),
('def_npc_gamma_termis_basic_lindy','def_named1_medium_driller',1,2,0.165),
('def_npc_gamma_termis_basic_lindy','def_named1_mining_probe_module',1,1,0.165),
('def_npc_gamma_termis_basic_lindy','def_named1_core_recharger',1,1,0.165),
('def_npc_gamma_termis_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_termis_basic_lindy','def_standard_medium_shield_generator',1,1,0.25),
('def_npc_gamma_termis_basic_lindy','def_standard_medium_driller',1,2,0.25),
('def_npc_gamma_termis_basic_lindy','def_standard_mining_probe_module',1,1,0.25),
('def_npc_gamma_termis_basic_lindy','def_standard_core_recharger',1,1,0.25),
('def_npc_gamma_termis_basic_lindy','def_ammo_mining_imentium',100,1000,0.5),
('def_npc_gamma_termis_basic_lindy','def_ammo_mining_stermonit',100,1000,0.5),
('def_npc_gamma_termis_basic_lindy','def_ammo_mining_silgium',100,1000,0.5),


('def_npc_gamma_gargoyle_basic_lindy','def_kernel_industrial',13312,19968,1),
('def_npc_gamma_gargoyle_basic_lindy','def_kernel_common',8320,12480,1),
('def_npc_gamma_gargoyle_basic_lindy','def_kernel_hitech',3328,4992,1),
('def_npc_gamma_gargoyle_basic_lindy','def_common_reactor_plasma',2832,3552,1),
('def_npc_gamma_gargoyle_basic_lindy','def_robotshard_common_expert',7,72,0.5),
('def_npc_gamma_gargoyle_basic_lindy','def_robotshard_common_advanced',7,72,0.5),
('def_npc_gamma_gargoyle_basic_lindy','def_robotshard_common_basic',7,72,0.5),
('def_npc_gamma_gargoyle_basic_lindy','def_named3_mining_upgrade',1,1,0.0825),
('def_npc_gamma_gargoyle_basic_lindy','def_named3_medium_shield_generator',1,1,0.0825),
('def_npc_gamma_gargoyle_basic_lindy','def_named3_medium_harvester',1,2,0.0825),
('def_npc_gamma_gargoyle_basic_lindy','def_named3_stealth_modul',1,1,0.0825),
('def_npc_gamma_gargoyle_basic_lindy','def_named3_core_recharger',1,1,0.0825),
('def_npc_gamma_gargoyle_basic_lindy','def_named2_mining_upgrade',1,1,0.09375),
('def_npc_gamma_gargoyle_basic_lindy','def_named2_medium_shield_generator',1,1,0.09375),
('def_npc_gamma_gargoyle_basic_lindy','def_named2_medium_harvester',1,2,0.09375),
('def_npc_gamma_gargoyle_basic_lindy','def_named2_stealth_modul',1,1,0.09375),
('def_npc_gamma_gargoyle_basic_lindy','def_named2_core_recharger',1,1,0.09375),
('def_npc_gamma_gargoyle_basic_lindy','def_named1_mining_upgrade',1,1,0.165),
('def_npc_gamma_gargoyle_basic_lindy','def_named1_medium_shield_generator',1,1,0.165),
('def_npc_gamma_gargoyle_basic_lindy','def_named1_medium_harvester',1,2,0.165),
('def_npc_gamma_gargoyle_basic_lindy','def_named1_stealth_modul',1,1,0.165),
('def_npc_gamma_gargoyle_basic_lindy','def_named1_core_recharger',1,1,0.165),
('def_npc_gamma_gargoyle_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_gargoyle_basic_lindy','def_standard_medium_shield_generator',1,1,0.25),
('def_npc_gamma_gargoyle_basic_lindy','def_standard_medium_harvester',1,2,0.25),
('def_npc_gamma_gargoyle_basic_lindy','def_standard_stealth_modul',1,1,0.25),
('def_npc_gamma_gargoyle_basic_lindy','def_standard_core_recharger',1,1,0.25),
('def_npc_gamma_gargoyle_basic_lindy','def_ammo_harvesting_standard',50,1250,1),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_electroplant',5,10,0.6),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_titanplant',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_bonsai',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_poffeteg',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_irontree',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_quag',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_pinetree',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_rango',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_rustbush',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_slimeroot',5,10,0.2),
('def_npc_gamma_gargoyle_basic_lindy','def_plant_seed_coppertree',5,10,0.2),


('def_npc_gamma_argano_basic_lindy','def_kernel_industrial',3328,4992,1),
('def_npc_gamma_argano_basic_lindy','def_kernel_common',2080,3120,1),
('def_npc_gamma_argano_basic_lindy','def_kernel_hitech',832,1248,1),
('def_npc_gamma_argano_basic_lindy','def_common_reactor_plasma',708,888,1),
('def_npc_gamma_argano_basic_lindy','def_robotshard_common_basic',4,36,0.5),
('def_npc_gamma_argano_basic_lindy','def_robotshard_common_advanced',2,24,0.5),
('def_npc_gamma_argano_basic_lindy','def_robotshard_common_expert',1,12,0.5),
('def_npc_gamma_argano_basic_lindy','def_named3_mining_upgrade',1,1,0.066),
('def_npc_gamma_argano_basic_lindy','def_named3_small_shield_generator',1,1,0.066),
('def_npc_gamma_argano_basic_lindy','def_named3_small_driller',1,2,0.066),
('def_npc_gamma_argano_basic_lindy','def_named3_mining_probe_module',1,1,0.066),
('def_npc_gamma_argano_basic_lindy','def_named3_small_core_battery',1,1,0.066),
('def_npc_gamma_argano_basic_lindy','def_named2_mining_upgrade',1,1,0.075),
('def_npc_gamma_argano_basic_lindy','def_named2_small_shield_generator',1,1,0.075),
('def_npc_gamma_argano_basic_lindy','def_named2_small_driller',1,2,0.075),
('def_npc_gamma_argano_basic_lindy','def_named2_mining_probe_module',1,1,0.075),
('def_npc_gamma_argano_basic_lindy','def_named2_small_core_battery',1,1,0.075),
('def_npc_gamma_argano_basic_lindy','def_named1_mining_upgrade',1,1,0.132),
('def_npc_gamma_argano_basic_lindy','def_named1_small_shield_generator',1,1,0.132),
('def_npc_gamma_argano_basic_lindy','def_named1_small_driller',1,2,0.132),
('def_npc_gamma_argano_basic_lindy','def_named1_mining_probe_module',1,1,0.132),
('def_npc_gamma_argano_basic_lindy','def_named1_small_core_battery',1,1,0.132),
('def_npc_gamma_argano_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_argano_basic_lindy','def_standard_small_shield_generator',1,1,0.25),
('def_npc_gamma_argano_basic_lindy','def_standard_small_driller',1,2,0.25),
('def_npc_gamma_argano_basic_lindy','def_standard_mining_probe_module',1,1,0.25),
('def_npc_gamma_argano_basic_lindy','def_standard_small_core_battery',1,1,0.25),
('def_npc_gamma_argano_basic_lindy','def_ammo_mining_imentium',50,250,0.5),
('def_npc_gamma_argano_basic_lindy','def_ammo_mining_stermonit',50,250,0.5),
('def_npc_gamma_argano_basic_lindy','def_ammo_mining_silgium',50,250,0.5),


('def_npc_gamma_laird_basic_lindy','def_kernel_industrial',3328,4992,1),
('def_npc_gamma_laird_basic_lindy','def_kernel_common',2080,3120,1),
('def_npc_gamma_laird_basic_lindy','def_kernel_hitech',832,1248,1),
('def_npc_gamma_laird_basic_lindy','def_common_reactor_plasma',708,888,1),
('def_npc_gamma_laird_basic_lindy','def_robotshard_common_basic',4,36,0.5),
('def_npc_gamma_laird_basic_lindy','def_robotshard_common_advanced',2,24,0.5),
('def_npc_gamma_laird_basic_lindy','def_robotshard_common_expert',1,12,0.5),
('def_npc_gamma_laird_basic_lindy','def_named3_mining_upgrade',1,1,0.066),
('def_npc_gamma_laird_basic_lindy','def_named3_small_shield_generator',1,1,0.066),
('def_npc_gamma_laird_basic_lindy','def_named3_small_harvester',1,2,0.066),
('def_npc_gamma_laird_basic_lindy','def_named3_stealth_modul',1,1,0.066),
('def_npc_gamma_laird_basic_lindy','def_named3_small_core_battery',1,1,0.066),
('def_npc_gamma_laird_basic_lindy','def_named2_mining_upgrade',1,1,0.075),
('def_npc_gamma_laird_basic_lindy','def_named2_small_shield_generator',1,1,0.075),
('def_npc_gamma_laird_basic_lindy','def_named2_small_harvester',1,2,0.075),
('def_npc_gamma_laird_basic_lindy','def_named2_stealth_modul',1,1,0.075),
('def_npc_gamma_laird_basic_lindy','def_named2_small_core_battery',1,1,0.075),
('def_npc_gamma_laird_basic_lindy','def_named1_mining_upgrade',1,1,0.132),
('def_npc_gamma_laird_basic_lindy','def_named1_small_shield_generator',1,1,0.132),
('def_npc_gamma_laird_basic_lindy','def_named1_small_harvester',1,2,0.132),
('def_npc_gamma_laird_basic_lindy','def_named1_stealth_modul',1,1,0.132),
('def_npc_gamma_laird_basic_lindy','def_named1_small_core_battery',1,1,0.132),
('def_npc_gamma_laird_basic_lindy','def_standard_mining_upgrade',1,1,0.25),
('def_npc_gamma_laird_basic_lindy','def_standard_small_shield_generator',1,1,0.25),
('def_npc_gamma_laird_basic_lindy','def_standard_small_harvester',1,2,0.25),
('def_npc_gamma_laird_basic_lindy','def_standard_stealth_modul',1,1,0.25),
('def_npc_gamma_laird_basic_lindy','def_standard_small_core_battery',1,1,0.25),
('def_npc_gamma_laird_basic_lindy','def_ammo_harvesting_standard',50,1250,1),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_electroplant',5,10,0.6),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_titanplant',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_bonsai',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_poffeteg',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_irontree',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_quag',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_pinetree',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_rango',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_rustbush',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_slimeroot',2,10,0.2),
('def_npc_gamma_laird_basic_lindy','def_plant_seed_coppertree',2,10,0.2),


('def_npc_gamma_hermes_basic_lindy','def_kernel_industrial',6656,9984,1),
('def_npc_gamma_hermes_basic_lindy','def_kernel_common',4160,6240,1),
('def_npc_gamma_hermes_basic_lindy','def_kernel_hitech',1664,2496,1),
('def_npc_gamma_hermes_basic_lindy','def_common_reactor_plasma',1416,1776,1),
('def_npc_gamma_hermes_basic_lindy','def_robotshard_common_expert',4,36,0.5),
('def_npc_gamma_hermes_basic_lindy','def_robotshard_common_advanced',7,72,0.5),
('def_npc_gamma_hermes_basic_lindy','def_robotshard_common_basic',11,108,0.5),
('def_npc_gamma_hermes_basic_lindy','def_ammo_small_projectile_d',100,200,0.5),
('def_npc_gamma_hermes_basic_lindy','def_ammo_artifact_scan_a',15,50,0.5),
('def_npc_gamma_hermes_basic_lindy','def_ammo_artifact_scan_b',15,50,0.3),
('def_npc_gamma_hermes_basic_lindy','def_ammo_artifact_scan_c',15,50,0.25),
('def_npc_gamma_hermes_basic_lindy','def_named3_mining_probe_module',1,1,0.066),
('def_npc_gamma_hermes_basic_lindy','def_named3_small_autocannon',1,1,0.066),
('def_npc_gamma_hermes_basic_lindy','def_named3_damage_mod_projectile',1,1,0.066),
('def_npc_gamma_hermes_basic_lindy','def_named3_small_armor_plate',1,1,0.066),
('def_npc_gamma_hermes_basic_lindy','def_named2_mining_probe_module',1,1,0.075),
('def_npc_gamma_hermes_basic_lindy','def_named2_small_autocannon',1,1,0.075),
('def_npc_gamma_hermes_basic_lindy','def_named2_damage_mod_projectile',1,1,0.075),
('def_npc_gamma_hermes_basic_lindy','def_named2_small_armor_plate',1,1,0.075),
('def_npc_gamma_hermes_basic_lindy','def_named1_mining_probe_module',1,1,0.132),
('def_npc_gamma_hermes_basic_lindy','def_named1_small_autocannon',1,1,0.132),
('def_npc_gamma_hermes_basic_lindy','def_named1_damage_mod_projectile',1,1,0.132),
('def_npc_gamma_hermes_basic_lindy','def_named1_small_armor_plate',1,1,0.132),
('def_npc_gamma_hermes_basic_lindy','def_standard_mining_probe_module',1,1,0.25),
('def_npc_gamma_hermes_basic_lindy','def_standard_small_autocannon',1,1,0.25),
('def_npc_gamma_hermes_basic_lindy','def_standard_damage_mod_projectile',1,1,0.25),
('def_npc_gamma_hermes_basic_lindy','def_standard_small_armor_plate',1,1,0.25),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_core_recharger',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_tracking_upgrade',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_maneuvering_upgrade',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_rocket_launcher',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_small_railgun',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_medium_armor_plate',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_medium_shield_generator',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_medium_laser',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_damage_mod_missile',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_sensor_booster',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_armor_repairer_upgrade',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_small_driller',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_medium_energy_neutralizer',1,1,0.1),
('def_npc_gamma_hermes_basic_lindy','def_artifact_damaged_medium_core_battery',1,1,0.1),


('def_npc_gamma_seth_advanced_observer','def_thelodica_reactor_plasma',27820,55640,1),
('def_npc_gamma_seth_advanced_observer','def_kernel_thelodica',26208,52416,1),
('def_npc_gamma_seth_advanced_observer','def_kernel_hitech',9360,18720,1),
('def_npc_gamma_seth_advanced_observer','def_kernel_common',11232,22464,1),
('def_npc_gamma_seth_advanced_observer','def_material_boss_gamma_thelodica',50,70,1),
('def_npc_gamma_seth_advanced_observer','def_ammo_medium_lasercrystal_rewb',100,200,0.5),
('def_npc_gamma_seth_advanced_observer','def_named3_medium_laser',1,1,0.22),
('def_npc_gamma_seth_advanced_observer','def_named3_resistant_plating',1,1,0.22),
('def_npc_gamma_seth_advanced_observer','def_named3_tracking_upgrade',1,1,0.22),
('def_npc_gamma_seth_advanced_observer','def_named3_damage_mod_laser',1,1,0.22),
('def_npc_gamma_seth_advanced_observer','def_named3_medium_armor_plate',1,1,0.22),
('def_npc_gamma_seth_advanced_observer','def_named2_medium_laser',1,1,0.33),
('def_npc_gamma_seth_advanced_observer','def_named2_resistant_plating',1,1,0.33),
('def_npc_gamma_seth_advanced_observer','def_named2_tracking_upgrade',1,1,0.33),
('def_npc_gamma_seth_advanced_observer','def_named2_damage_mod_laser',1,1,0.33),
('def_npc_gamma_seth_advanced_observer','def_named2_medium_armor_plate',1,1,0.33),
('def_npc_gamma_seth_advanced_observer','def_reactore_core_heavymech',1,1,0.1),
('def_npc_gamma_seth_advanced_observer','def_research_kit_7',1,1,0.1),
('def_npc_gamma_seth_advanced_observer','def_research_kit_8',1,1,0.1),


('def_npc_gamma_artemis_advanced_observer','def_thelodica_reactor_plasma',20020,40040,1),
('def_npc_gamma_artemis_advanced_observer','def_kernel_thelodica',13923,27846,1),
('def_npc_gamma_artemis_advanced_observer','def_kernel_hitech',7800,15600,1),
('def_npc_gamma_artemis_advanced_observer','def_kernel_common',5967,11934,1),
('def_npc_gamma_artemis_advanced_observer','def_material_boss_gamma_thelodica',20,30,1),
('def_npc_gamma_artemis_advanced_observer','def_ammo_medium_lasercrystal_rewa',100,150,0.5),
('def_npc_gamma_artemis_advanced_observer','def_named3_medium_laser',1,1,0.22),
('def_npc_gamma_artemis_advanced_observer','def_named3_resistant_plating',1,1,0.22),
('def_npc_gamma_artemis_advanced_observer','def_named3_tracking_upgrade',1,1,0.22),
('def_npc_gamma_artemis_advanced_observer','def_named3_damage_mod_laser',1,1,0.22),
('def_npc_gamma_artemis_advanced_observer','def_named2_medium_laser',1,1,0.33),
('def_npc_gamma_artemis_advanced_observer','def_named2_resistant_plating',1,1,0.33),
('def_npc_gamma_artemis_advanced_observer','def_named2_tracking_upgrade',1,1,0.33),
('def_npc_gamma_artemis_advanced_observer','def_named2_damage_mod_laser',1,1,0.33),
('def_npc_gamma_artemis_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_artemis_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_artemis_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_zenith_advanced_observer','def_thelodica_reactor_plasma',20020,40040,1),
('def_npc_gamma_zenith_advanced_observer','def_kernel_thelodica',8463,16926,1),
('def_npc_gamma_zenith_advanced_observer','def_kernel_hitech',7800,15600,1),
('def_npc_gamma_zenith_advanced_observer','def_kernel_common',3627,7254,1),
('def_npc_gamma_zenith_advanced_observer','def_material_boss_gamma_thelodica',20,40,1),
('def_npc_gamma_zenith_advanced_observer','def_ammo_medium_lasercrystal_rewb',50,100,0.5),
('def_npc_gamma_zenith_advanced_observer','def_named3_longrange_medium_laser',1,1,0.22),
('def_npc_gamma_zenith_advanced_observer','def_named3_resistant_plating',1,1,0.22),
('def_npc_gamma_zenith_advanced_observer','def_named3_sensor_dampener',1,1,0.22),
('def_npc_gamma_zenith_advanced_observer','def_named3_sensor_supressor_booster',1,1,0.22),
('def_npc_gamma_zenith_advanced_observer','def_named2_longrange_medium_laser',1,1,0.33),
('def_npc_gamma_zenith_advanced_observer','def_named2_resistant_plating',1,1,0.33),
('def_npc_gamma_zenith_advanced_observer','def_named2_sensor_dampener',1,1,0.33),
('def_npc_gamma_zenith_advanced_observer','def_named2_sensor_supressor_booster',1,1,0.33),
('def_npc_gamma_zenith_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_zenith_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_zenith_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_gropho_advanced_observer','def_pelistal_reactor_plasma',27820,55640,1),
('def_npc_gamma_gropho_advanced_observer','def_kernel_pelistal',26208,52416,1),
('def_npc_gamma_gropho_advanced_observer','def_kernel_hitech',9360,18720,1),
('def_npc_gamma_gropho_advanced_observer','def_kernel_common',11232,22464,1),
('def_npc_gamma_gropho_advanced_observer','def_material_boss_gamma_pelistal',50,70,1),
('def_npc_gamma_gropho_advanced_observer','def_ammo_missile_rewb',50,100,0.5),
('def_npc_gamma_gropho_advanced_observer','def_named3_missile_launcher',1,1,0.22),
('def_npc_gamma_gropho_advanced_observer','def_named3_core_recharger',1,1,0.22),
('def_npc_gamma_gropho_advanced_observer','def_named3_tracking_upgrade',1,1,0.22),
('def_npc_gamma_gropho_advanced_observer','def_named3_damage_mod_missile',1,1,0.22),
('def_npc_gamma_gropho_advanced_observer','def_named3_medium_shield_generator',1,1,0.22),
('def_npc_gamma_gropho_advanced_observer','def_named2_missile_launcher',1,1,0.33),
('def_npc_gamma_gropho_advanced_observer','def_named2_core_recharger',1,1,0.33),
('def_npc_gamma_gropho_advanced_observer','def_named2_tracking_upgrade',1,1,0.33),
('def_npc_gamma_gropho_advanced_observer','def_named2_damage_mod_missile',1,1,0.33),
('def_npc_gamma_gropho_advanced_observer','def_named2_medium_shield_generator',1,1,0.33),
('def_npc_gamma_gropho_advanced_observer','def_reactore_core_heavymech',1,1,0.1),
('def_npc_gamma_gropho_advanced_observer','def_research_kit_7',1,1,0.1),
('def_npc_gamma_gropho_advanced_observer','def_research_kit_8',1,1,0.1),


('def_npc_gamma_tyrannos_advanced_observer','def_pelistal_reactor_plasma',20020,40040,1),
('def_npc_gamma_tyrannos_advanced_observer','def_kernel_pelistal',13923,27846,1),
('def_npc_gamma_tyrannos_advanced_observer','def_kernel_hitech',7800,15600,1),
('def_npc_gamma_tyrannos_advanced_observer','def_kernel_common',5967,11934,1),
('def_npc_gamma_tyrannos_advanced_observer','def_material_boss_gamma_pelistal',20,30,1),
('def_npc_gamma_tyrannos_advanced_observer','def_ammo_missile_rewa',50,75,0.5),
('def_npc_gamma_tyrannos_advanced_observer','def_named3_missile_launcher',1,1,0.22),
('def_npc_gamma_tyrannos_advanced_observer','def_named3_medium_energy_vampire',1,1,0.22),
('def_npc_gamma_tyrannos_advanced_observer','def_named3_damage_mod_missile',1,1,0.22),
('def_npc_gamma_tyrannos_advanced_observer','def_named3_medium_shield_generator',1,1,0.22),
('def_npc_gamma_tyrannos_advanced_observer','def_named2_missile_launcher',1,1,0.33),
('def_npc_gamma_tyrannos_advanced_observer','def_named2_medium_energy_vampire',1,1,0.33),
('def_npc_gamma_tyrannos_advanced_observer','def_named2_damage_mod_missile',1,1,0.33),
('def_npc_gamma_tyrannos_advanced_observer','def_named2_medium_shield_generator',1,1,0.33),
('def_npc_gamma_tyrannos_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_tyrannos_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_tyrannos_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_ictus_advanced_observer','def_pelistal_reactor_plasma',20020,40040,1),
('def_npc_gamma_ictus_advanced_observer','def_kernel_pelistal',8463,16926,1),
('def_npc_gamma_ictus_advanced_observer','def_kernel_hitech',7800,15600,1),
('def_npc_gamma_ictus_advanced_observer','def_kernel_common',3627,7254,1),
('def_npc_gamma_ictus_advanced_observer','def_material_boss_gamma_pelistal',20,40,1),
('def_npc_gamma_ictus_advanced_observer','def_ammo_longrange_missile_rewb',50,75,0.5),
('def_npc_gamma_ictus_advanced_observer','def_named3_missile_launcher',1,1,0.22),
('def_npc_gamma_ictus_advanced_observer','def_named3_energy_warfare_upgrade',1,1,0.22),
('def_npc_gamma_ictus_advanced_observer','def_named3_shield_hardener',1,1,0.22),
('def_npc_gamma_ictus_advanced_observer','def_named3_medium_energy_neutralizer',1,1,0.22),
('def_npc_gamma_ictus_advanced_observer','def_named2_missile_launcher',1,1,0.33),
('def_npc_gamma_ictus_advanced_observer','def_named2_energy_warfare_upgrade',1,1,0.33),
('def_npc_gamma_ictus_advanced_observer','def_named2_shield_hardener',1,1,0.33),
('def_npc_gamma_ictus_advanced_observer','def_named2_medium_energy_neutralizer',1,1,0.33),
('def_npc_gamma_ictus_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_ictus_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_ictus_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_mesmer_advanced_observer','def_nuimqol_reactor_plasma',27820,55640,1),
('def_npc_gamma_mesmer_advanced_observer','def_kernel_nuimqol',26208,52416,1),
('def_npc_gamma_mesmer_advanced_observer','def_kernel_hitech',9360,18720,1),
('def_npc_gamma_mesmer_advanced_observer','def_kernel_common',11232,22464,1),
('def_npc_gamma_mesmer_advanced_observer','def_material_boss_gamma_nuimqol',50,70,1),
('def_npc_gamma_mesmer_advanced_observer','def_ammo_medium_railgun_rewb',100,200,0.5),
('def_npc_gamma_mesmer_advanced_observer','def_named3_medium_railgun',1,1,0.22),
('def_npc_gamma_mesmer_advanced_observer','def_named3_medium_core_booster',1,1,0.22),
('def_npc_gamma_mesmer_advanced_observer','def_named3_tracking_upgrade',1,1,0.22),
('def_npc_gamma_mesmer_advanced_observer','def_named3_damage_mod_railgun',1,1,0.22),
('def_npc_gamma_mesmer_advanced_observer','def_named3_medium_armor_repairer',1,1,0.22),
('def_npc_gamma_mesmer_advanced_observer','def_named2_medium_railgun',1,1,0.33),
('def_npc_gamma_mesmer_advanced_observer','def_named2_medium_core_booster',1,1,0.33),
('def_npc_gamma_mesmer_advanced_observer','def_named2_tracking_upgrade',1,1,0.33),
('def_npc_gamma_mesmer_advanced_observer','def_named2_damage_mod_railgun',1,1,0.33),
('def_npc_gamma_mesmer_advanced_observer','def_named2_medium_armor_repairer',1,1,0.33),
('def_npc_gamma_mesmer_advanced_observer','def_reactore_core_heavymech',1,1,0.1),
('def_npc_gamma_mesmer_advanced_observer','def_research_kit_7',1,1,0.1),
('def_npc_gamma_mesmer_advanced_observer','def_research_kit_8',1,1,0.1),


('def_npc_gamma_kain_advanced_observer','def_nuimqol_reactor_plasma',20020,40040,1),
('def_npc_gamma_kain_advanced_observer','def_kernel_nuimqol',13923,27846,1),
('def_npc_gamma_kain_advanced_observer','def_kernel_hitech',7800,15600,1),
('def_npc_gamma_kain_advanced_observer','def_kernel_common',5967,11934,1),
('def_npc_gamma_kain_advanced_observer','def_material_boss_gamma_nuimqol',20,30,1),
('def_npc_gamma_kain_advanced_observer','def_ammo_medium_railgun_rewa',100,150,0.5),
('def_npc_gamma_kain_advanced_observer','def_named3_medium_railgun',1,1,0.22),
('def_npc_gamma_kain_advanced_observer','def_named3_tracking_upgrade',1,1,0.22),
('def_npc_gamma_kain_advanced_observer','def_named3_damage_mod_railgun',1,1,0.22),
('def_npc_gamma_kain_advanced_observer','def_named3_medium_armor_repairer',1,1,0.22),
('def_npc_gamma_kain_advanced_observer','def_named2_medium_railgun',1,1,0.33),
('def_npc_gamma_kain_advanced_observer','def_named2_tracking_upgrade',1,1,0.33),
('def_npc_gamma_kain_advanced_observer','def_named2_damage_mod_railgun',1,1,0.33),
('def_npc_gamma_kain_advanced_observer','def_named2_medium_armor_repairer',1,1,0.33),
('def_npc_gamma_kain_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_kain_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_kain_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_vagabond_advanced_observer','def_nuimqol_reactor_plasma',20020,40040,1),
('def_npc_gamma_vagabond_advanced_observer','def_kernel_nuimqol',8463,16926,1),
('def_npc_gamma_vagabond_advanced_observer','def_kernel_hitech',7800,15600,1),
('def_npc_gamma_vagabond_advanced_observer','def_kernel_common',3627,7254,1),
('def_npc_gamma_vagabond_advanced_observer','def_material_boss_gamma_nuimqol',20,40,1),
('def_npc_gamma_vagabond_advanced_observer','def_ammo_medium_railgun_rewb',50,100,0.5),
('def_npc_gamma_vagabond_advanced_observer','def_named3_longrange_medium_railgun',1,1,0.22),
('def_npc_gamma_vagabond_advanced_observer','def_named3_medium_core_battery',1,1,0.22),
('def_npc_gamma_vagabond_advanced_observer','def_named3_sensor_jammer',1,1,0.22),
('def_npc_gamma_vagabond_advanced_observer','def_named3_ecm_booster',1,1,0.22),
('def_npc_gamma_vagabond_advanced_observer','def_named2_longrange_medium_railgun',1,1,0.33),
('def_npc_gamma_vagabond_advanced_observer','def_named2_medium_core_battery',1,1,0.33),
('def_npc_gamma_vagabond_advanced_observer','def_named2_sensor_jammer',1,1,0.33),
('def_npc_gamma_vagabond_advanced_observer','def_named2_ecm_booster',1,1,0.33),
('def_npc_gamma_vagabond_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_vagabond_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_vagabond_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_legatus_advanced_observer','def_common_reactor_plasma',33384,66768,1),
('def_npc_gamma_legatus_advanced_observer','def_kernel_common',33696,67392,1),
('def_npc_gamma_legatus_advanced_observer','def_kernel_hitech',18720,37440,1),
('def_npc_gamma_legatus_advanced_observer','def_material_boss_gamma_syndicate',50,70,1),
('def_npc_gamma_legatus_advanced_observer','def_ammo_medium_projectile_rewb',150,300,0.5),
('def_npc_gamma_legatus_advanced_observer','def_named3_medium_autocannon',1,1,0.22),
('def_npc_gamma_legatus_advanced_observer','def_named3_resistant_plating',1,1,0.22),
('def_npc_gamma_legatus_advanced_observer','def_named3_tracking_upgrade',1,1,0.22),
('def_npc_gamma_legatus_advanced_observer','def_named3_damage_mod_projectile',1,1,0.22),
('def_npc_gamma_legatus_advanced_observer','def_named2_large_armor_plate',1,1,0.22),
('def_npc_gamma_legatus_advanced_observer','def_named2_medium_autocannon',1,1,0.33),
('def_npc_gamma_legatus_advanced_observer','def_named2_resistant_plating',1,1,0.33),
('def_npc_gamma_legatus_advanced_observer','def_named2_tracking_upgrade',1,1,0.33),
('def_npc_gamma_legatus_advanced_observer','def_named2_damage_mod_projectile',1,1,0.33),
('def_npc_gamma_legatus_advanced_observer','def_named1_large_armor_plate',1,1,0.33),
('def_npc_gamma_legatus_advanced_observer','def_reactore_core_heavymech',1,1,0.1),
('def_npc_gamma_legatus_advanced_observer','def_research_kit_7',1,1,0.1),
('def_npc_gamma_legatus_advanced_observer','def_research_kit_8',1,1,0.1),


('def_npc_gamma_echelon_advanced_observer','def_common_reactor_plasma',24024,48048,1),
('def_npc_gamma_echelon_advanced_observer','def_kernel_common',17901,35802,1),
('def_npc_gamma_echelon_advanced_observer','def_kernel_hitech',15600,31200,1),
('def_npc_gamma_echelon_advanced_observer','def_material_boss_gamma_syndicate',20,30,1),
('def_npc_gamma_echelon_advanced_observer','def_ammo_medium_projectile_rewa',100,150,0.5),
('def_npc_gamma_echelon_advanced_observer','def_named3_medium_autocannon',1,1,0.22),
('def_npc_gamma_echelon_advanced_observer','def_named3_webber',1,1,0.22),
('def_npc_gamma_echelon_advanced_observer','def_named3_sensor_booster',1,1,0.22),
('def_npc_gamma_echelon_advanced_observer','def_named3_damage_mod_projectile',1,1,0.22),
('def_npc_gamma_echelon_advanced_observer','def_named2_medium_autocannon',1,1,0.33),
('def_npc_gamma_echelon_advanced_observer','def_named2_webber',1,1,0.33),
('def_npc_gamma_echelon_advanced_observer','def_named2_sensor_booster',1,1,0.33),
('def_npc_gamma_echelon_advanced_observer','def_named2_damage_mod_projectile',1,1,0.33),
('def_npc_gamma_echelon_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_echelon_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_echelon_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_callisto_advanced_observer','def_common_reactor_plasma',24024,48048,1),
('def_npc_gamma_callisto_advanced_observer','def_kernel_common',10881,21762,1),
('def_npc_gamma_callisto_advanced_observer','def_kernel_hitech',15600,31200,1),
('def_npc_gamma_callisto_advanced_observer','def_material_boss_gamma_syndicate',20,40,1),
('def_npc_gamma_callisto_advanced_observer','def_ammo_medium_projectile_rewb',50,100,0.5),
('def_npc_gamma_callisto_advanced_observer','def_named3_longrange_medium_autocannon',1,1,0.22),
('def_npc_gamma_callisto_advanced_observer','def_named3_longrange_webber',1,1,0.22),
('def_npc_gamma_callisto_advanced_observer','def_named3_sensor_dampener',1,1,0.22),
('def_npc_gamma_callisto_advanced_observer','def_named3_sensor_jammer',1,1,0.22),
('def_npc_gamma_callisto_advanced_observer','def_named2_longrange_medium_autocannon',1,1,0.33),
('def_npc_gamma_callisto_advanced_observer','def_named2_longrange_webber',1,1,0.33),
('def_npc_gamma_callisto_advanced_observer','def_named2_sensor_dampener',1,1,0.33),
('def_npc_gamma_callisto_advanced_observer','def_named2_sensor_jammer',1,1,0.33),
('def_npc_gamma_callisto_advanced_observer','def_reactore_core_mech',1,1,0.1),
('def_npc_gamma_callisto_advanced_observer','def_research_kit_7',1,1,0.05),
('def_npc_gamma_callisto_advanced_observer','def_research_kit_8',1,1,0.05),


('def_npc_gamma_seth_boss_miniboss','def_thelodica_reactor_plasma',75000,150000,1),
('def_npc_gamma_seth_boss_miniboss','def_kernel_thelodica',37500,75000,1),
('def_npc_gamma_seth_boss_miniboss','def_kernel_hitech',37500,75000,1),
('def_npc_gamma_seth_boss_miniboss','def_kernel_common',37500,75000,1),
('def_npc_gamma_seth_boss_miniboss','def_material_boss_gamma_thelodica',500,700,1),
('def_npc_gamma_seth_boss_miniboss','def_ammo_medium_lasercrystal_rewb',600,1800,1),
('def_npc_gamma_seth_boss_miniboss','def_ammo_medium_lasercrystal_rewa',600,1800,1),
('def_npc_gamma_seth_boss_miniboss','def_named3_medium_laser',1,3,0.44),
('def_npc_gamma_seth_boss_miniboss','def_named3_resistant_plating',1,1,0.44),
('def_npc_gamma_seth_boss_miniboss','def_named3_armor_repairer_upgrade',1,1,0.44),
('def_npc_gamma_seth_boss_miniboss','def_named3_damage_mod_laser',1,1,0.44),
('def_npc_gamma_seth_boss_miniboss','def_named3_large_armor_plate',1,1,0.22),
('def_npc_gamma_seth_boss_miniboss','def_reactore_core_heavymech',1,2,0.3),
('def_npc_gamma_seth_boss_miniboss','def_reactore_core_mech',1,2,0.3),
('def_npc_gamma_seth_boss_miniboss','def_reactore_core_assault',1,2,0.3),
('def_npc_gamma_seth_boss_miniboss','def_reactore_core_runner',1,2,0.3),
('def_npc_gamma_seth_boss_miniboss','def_research_kit_8',1,1,0.3),
('def_npc_gamma_seth_boss_miniboss','def_research_kit_9',1,1,0.3),
('def_npc_gamma_seth_boss_miniboss','def_boost_ep_t0',1,1,0.3),
('def_npc_gamma_seth_boss_miniboss','def_seth_mk2_A_CT_capsule',1,1,0.3),
('def_npc_gamma_seth_boss_miniboss','def_artemis_mk2_A_CT_capsule',1,1,0.3),
('def_npc_gamma_seth_boss_miniboss','def_zenith_mk2_A_CT_capsule',1,1,0.3),


('def_npc_gamma_gropho_boss_miniboss','def_pelistal_reactor_plasma',75000,150000,1),
('def_npc_gamma_gropho_boss_miniboss','def_kernel_pelistal',37500,75000,1),
('def_npc_gamma_gropho_boss_miniboss','def_kernel_hitech',37500,75000,1),
('def_npc_gamma_gropho_boss_miniboss','def_kernel_common',37500,75000,1),
('def_npc_gamma_gropho_boss_miniboss','def_material_boss_gamma_pelistal',500,700,1),
('def_npc_gamma_gropho_boss_miniboss','def_ammo_missile_rewa',300,800,1),
('def_npc_gamma_gropho_boss_miniboss','def_ammo_missile_rewb',300,800,1),
('def_npc_gamma_gropho_boss_miniboss','def_ammo_longrange_missile_rewa',300,800,1),
('def_npc_gamma_gropho_boss_miniboss','def_ammo_longrange_missile_rewb',300,800,1),
('def_npc_gamma_gropho_boss_miniboss','def_named3_missile_launcher',1,3,0.44),
('def_npc_gamma_gropho_boss_miniboss','def_named3_thrm_armor_hardener',1,1,0.44),
('def_npc_gamma_gropho_boss_miniboss','def_named3_shield_hardener',1,2,0.44),
('def_npc_gamma_gropho_boss_miniboss','def_named3_damage_mod_missile',1,1,0.44),
('def_npc_gamma_gropho_boss_miniboss','def_named3_core_recharger',1,2,0.44),
('def_npc_gamma_gropho_boss_miniboss','def_reactore_core_heavymech',1,2,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_reactore_core_mech',1,2,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_reactore_core_assault',1,2,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_reactore_core_runner',1,2,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_research_kit_8',1,1,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_research_kit_9',1,1,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_boost_ep_t0',1,1,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_gropho_mk2_A_CT_capsule',1,1,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_tyrannos_mk2_A_CT_capsule',1,1,0.3),
('def_npc_gamma_gropho_boss_miniboss','def_ictus_mk2_A_CT_capsule',1,1,0.3),


('def_npc_gamma_mesmer_boss_miniboss','def_nuimqol_reactor_plasma',75000,150000,1),
('def_npc_gamma_mesmer_boss_miniboss','def_kernel_nuimqol',37500,75000,1),
('def_npc_gamma_mesmer_boss_miniboss','def_kernel_hitech',37500,75000,1),
('def_npc_gamma_mesmer_boss_miniboss','def_kernel_common',37500,75000,1),
('def_npc_gamma_mesmer_boss_miniboss','def_material_boss_gamma_nuimqol',500,700,1),
('def_npc_gamma_mesmer_boss_miniboss','def_ammo_medium_railgun_rewb',450,1200,1),
('def_npc_gamma_mesmer_boss_miniboss','def_ammo_medium_railgun_rewa',450,1200,1),
('def_npc_gamma_mesmer_boss_miniboss','def_named3_medium_railgun',1,3,0.44),
('def_npc_gamma_mesmer_boss_miniboss','def_named3_medium_armor_repairer',1,2,0.44),
('def_npc_gamma_mesmer_boss_miniboss','def_named3_armor_repairer_upgrade',1,2,0.44),
('def_npc_gamma_mesmer_boss_miniboss','def_named3_damage_mod_railgun',1,1,0.44),
('def_npc_gamma_mesmer_boss_miniboss','def_named3_medium_core_booster',1,1,0.44),
('def_npc_gamma_mesmer_boss_miniboss','def_reactore_core_heavymech',1,2,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_reactore_core_mech',1,2,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_reactore_core_assault',1,2,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_reactore_core_runner',1,2,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_research_kit_8',1,1,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_research_kit_9',1,1,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_boost_ep_t0',1,1,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_mesmer_mk2_A_CT_capsule',1,1,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_kain_mk2_A_CT_capsule',1,1,0.3),
('def_npc_gamma_mesmer_boss_miniboss','def_vagabond_mk2_A_CT_capsule',1,1,0.3),


('def_npc_gamma_legatus_boss_miniboss','def_common_reactor_plasma',100000,200000,1),
('def_npc_gamma_legatus_boss_miniboss','def_kernel_hitech',50000,100000,1),
('def_npc_gamma_legatus_boss_miniboss','def_kernel_common',50000,100000,1),
('def_npc_gamma_legatus_boss_miniboss','def_material_boss_gamma_syndicate',500,700,1),
('def_npc_gamma_legatus_boss_miniboss','def_ammo_medium_projectile_rewb',600,1800,1),
('def_npc_gamma_legatus_boss_miniboss','def_ammo_medium_projectile_rewa',600,1800,1),
('def_npc_gamma_legatus_boss_miniboss','def_named3_medium_autocannon',1,3,0.44),
('def_npc_gamma_legatus_boss_miniboss','def_named3_resistant_plating',1,1,0.44),
('def_npc_gamma_legatus_boss_miniboss','def_named3_armor_repairer_upgrade',1,1,0.44),
('def_npc_gamma_legatus_boss_miniboss','def_named3_damage_mod_projectile',1,2,0.44),
('def_npc_gamma_legatus_boss_miniboss','def_named3_large_armor_plate',1,1,0.44),
('def_npc_gamma_legatus_boss_miniboss','def_reactore_core_heavymech',1,2,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_reactore_core_mech',1,2,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_reactore_core_assault',1,2,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_reactore_core_runner',1,2,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_research_kit_8',1,1,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_research_kit_9',1,1,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_boost_ep_t0',1,1,0.3),
('def_npc_gamma_legatus_boss_miniboss','def_boost_ep_t1',1,1,0.3),


('def_npc_gamma_onyx_mammoth_destro','def_thelodica_reactor_plasma',100000,200000,1),
('def_npc_gamma_onyx_mammoth_destro','def_kernel_thelodica',50000,100000,1),
('def_npc_gamma_onyx_mammoth_destro','def_kernel_hitech',50000,100000,1),
('def_npc_gamma_onyx_mammoth_destro','def_kernel_common',50000,100000,1),
('def_npc_gamma_onyx_mammoth_destro','def_material_boss_gamma_thelodica',100,200,1),
('def_npc_gamma_onyx_mammoth_destro','def_ammo_large_lasercrystal_rewa',2700,3600,1),
('def_npc_gamma_onyx_mammoth_destro','def_ammo_large_lasercrystal_d',200,600,1),
('def_npc_gamma_onyx_mammoth_destro','def_named3_longrange_large_laser',1,3,0.5),
('def_npc_gamma_onyx_mammoth_destro','def_named3_large_armor_plate',1,1,0.5),
('def_npc_gamma_onyx_mammoth_destro','def_named3_large_armor_repairer',1,1,0.5),
('def_npc_gamma_onyx_mammoth_destro','def_named3_resistant_plating',1,1,1),
('def_npc_gamma_onyx_mammoth_destro','def_reactore_core_heavymech',1,3,1),
('def_npc_gamma_onyx_mammoth_destro','def_boost_ep_t1',1,2,1),


('def_npc_gamma_hydra_mammoth_destro','def_pelistal_reactor_plasma',100000,200000,1),
('def_npc_gamma_hydra_mammoth_destro','def_kernel_pelistal',50000,100000,1),
('def_npc_gamma_hydra_mammoth_destro','def_kernel_hitech',50000,100000,1),
('def_npc_gamma_hydra_mammoth_destro','def_kernel_common',50000,100000,1),
('def_npc_gamma_hydra_mammoth_destro','def_material_boss_gamma_pelistal',100,200,1),
('def_npc_gamma_hydra_mammoth_destro','def_ammo_longrange_cruisemissile_rewa',900,1200,1),
('def_npc_gamma_hydra_mammoth_destro','def_ammo_cruisemissile_rewa',900,1200,1),
('def_npc_gamma_hydra_mammoth_destro','def_ammo_longrange_cruisemissile_d',75,200,1),
('def_npc_gamma_hydra_mammoth_destro','def_ammo_cruisemissile_d',75,200,1),
('def_npc_gamma_hydra_mammoth_destro','def_named3_cruisemissile_launcher',1,3,0.5),
('def_npc_gamma_hydra_mammoth_destro','def_named3_large_shield_generator',1,1,0.5),
('def_npc_gamma_hydra_mammoth_destro','def_named3_large_armor_repairer',1,1,0.5),
('def_npc_gamma_hydra_mammoth_destro','def_named3_shield_hardener',1,1,1),
('def_npc_gamma_hydra_mammoth_destro','def_reactore_core_heavymech',1,3,1),
('def_npc_gamma_hydra_mammoth_destro','def_boost_ep_t1',1,2,1),


('def_npc_gamma_felos_mammoth_destro','def_nuimqol_reactor_plasma',100000,200000,1),
('def_npc_gamma_felos_mammoth_destro','def_kernel_nuimqol',50000,100000,1),
('def_npc_gamma_felos_mammoth_destro','def_kernel_hitech',50000,100000,1),
('def_npc_gamma_felos_mammoth_destro','def_kernel_common',50000,100000,1),
('def_npc_gamma_felos_mammoth_destro','def_material_boss_gamma_nuimqol',100,200,1),
('def_npc_gamma_felos_mammoth_destro','def_ammo_large_railgun_rewa',1800,2700,1),
('def_npc_gamma_felos_mammoth_destro','def_ammo_large_railgun_d',125,450,1),
('def_npc_gamma_felos_mammoth_destro','def_named3_longrange_large_railgun',1,3,0.5),
('def_npc_gamma_felos_mammoth_destro','def_named3_large_core_booster',1,1,0.5),
('def_npc_gamma_felos_mammoth_destro','def_named3_large_armor_repairer',1,1,0.5),
('def_npc_gamma_felos_mammoth_destro','def_named3_resistant_plating',1,1,1),
('def_npc_gamma_felos_mammoth_destro','def_reactore_core_heavymech',1,3,1),
('def_npc_gamma_felos_mammoth_destro','def_boost_ep_t1',1,2,1),


('def_npc_gamma_onyx_thelodica_pitboss','def_thelodica_reactor_plasma',150000,300000,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_kernel_thelodica',105000,210000,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_kernel_hitech',105000,210000,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_kernel_common',105000,210000,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_material_boss_gamma_thelodica',10000,14000,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_ammo_large_lasercrystal_b',300,900,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_large_laser',2,3,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_large_armor_plate',1,2,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_large_armor_repairer',1,1,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_resistant_plating',1,2,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_armor_repairer_upgrade',1,2,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_gang_assist_precision_firing_module',1,1,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_named3_gang_assist_defense_module',1,1,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_reactore_core_heavymech',2,4,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_reactore_core_mech',2,4,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_reactore_core_assault',2,4,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_reactore_core_runner',2,4,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_boost_ep_t0',2,4,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_boost_ep_t1',2,3,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_boost_ep_t2',1,2,1),
('def_npc_gamma_onyx_thelodica_pitboss','def_boost_ep_t3',1,1,1),


('def_npc_gamma_hydra_pelistal_pitboss','def_pelistal_reactor_plasma',150000,300000,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_kernel_pelistal',105000,210000,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_kernel_hitech',105000,210000,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_kernel_common',105000,210000,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_material_boss_gamma_pelistal',10000,14000,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_ammo_longrange_cruisemissile_a',200,500,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_cruisemissile_launcher',2,3,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_large_shield_generator',1,1,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_large_armor_repairer',1,1,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_resistant_plating',1,2,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_shield_hardener',1,2,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_gang_assist_shared_dataprocessing_module',1,1,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_named3_gang_assist_shield_calculation_module',1,1,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_reactore_core_heavymech',2,4,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_reactore_core_mech',2,4,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_reactore_core_assault',2,4,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_reactore_core_runner',2,4,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_boost_ep_t0',2,4,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_boost_ep_t1',2,3,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_boost_ep_t2',1,2,1),
('def_npc_gamma_hydra_pelistal_pitboss','def_boost_ep_t3',1,1,1),


('def_npc_gamma_felos_nuimqol_pitboss','def_nuimqol_reactor_plasma',150000,300000,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_kernel_nuimqol',105000,210000,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_kernel_hitech',105000,210000,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_kernel_common',105000,210000,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_material_boss_gamma_nuimqol',10000,14000,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_ammo_large_railgun_a',600,1000,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_large_railgun',2,3,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_large_armor_plate',1,1,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_large_armor_repairer',1,2,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_resistant_plating',1,1,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_armor_repairer_upgrade',1,2,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_gang_assist_siege_module',1,1,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_named3_gang_assist_maintance_module',1,1,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_reactore_core_heavymech',2,4,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_reactore_core_mech',2,4,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_reactore_core_assault',2,4,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_reactore_core_runner',2,4,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_boost_ep_t0',2,4,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_boost_ep_t1',2,3,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_boost_ep_t2',1,2,1),
('def_npc_gamma_felos_nuimqol_pitboss','def_boost_ep_t3',1,1,1),


('def_npc_gamma_apollo_syndicate_syn_pitboss','def_common_reactor_plasma',225000,450000,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_kernel_hitech',150000,300000,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_kernel_common',150000,300000,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_material_boss_gamma_syndicate',10000,14000,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_named3_large_armor_plate',1,2,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_named3_large_armor_repairer',1,1,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_named3_resistant_plating',1,2,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_named3_armor_repairer_upgrade',1,2,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_standard_blob_emission_modulator',1,1,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_named3_gang_assist_coordinated_maneuvering_module',1,1,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_named3_gang_assist_ewar_range_module',1,1,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_reactore_core_heavymech',2,4,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_reactore_core_mech',2,4,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_reactore_core_assault',2,4,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_reactore_core_runner',2,4,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_boost_ep_t0',2,4,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_boost_ep_t1',2,3,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_boost_ep_t2',1,2,1),
('def_npc_gamma_apollo_syndicate_syn_pitboss','def_boost_ep_t3',1,1,1);

INSERT INTO #LOOTS (defName, lootName, minQuant, maxQuant, prob) VALUES
('def_npc_gamma_baphomet_advanced_courier','def_thelodica_reactor_plasma',2340,9360,1),
('def_npc_gamma_baphomet_advanced_courier','def_kernel_thelodica',3549,14196,1),
('def_npc_gamma_baphomet_advanced_courier','def_kernel_hitech',1300,5200,1),
('def_npc_gamma_baphomet_advanced_courier','def_kernel_common',1521,6084,1),
('def_npc_gamma_baphomet_advanced_courier','def_material_boss_gamma_thelodica',100,140,1),
('def_npc_gamma_baphomet_advanced_courier','def_ammo_small_lasercrystal_rewb',150,200,0.5),
('def_npc_gamma_baphomet_advanced_courier','def_ammo_medium_lasercrystal_rewa',80,120,0.5),
('def_npc_gamma_baphomet_advanced_courier','def_named3_medium_laser',1,1,0.22),
('def_npc_gamma_baphomet_advanced_courier','def_named3_small_laser',1,1,0.33),
('def_npc_gamma_baphomet_advanced_courier','def_named3_resistant_plating',1,1,0.22),
('def_npc_gamma_baphomet_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_baphomet_advanced_courier','def_named3_damage_mod_laser',1,1,0.22),
('def_npc_gamma_baphomet_advanced_courier','def_reactore_core_assault',1,1,0.75),
('def_npc_gamma_baphomet_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_baphomet_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_prometheus_advanced_courier','def_thelodica_reactor_plasma',1248,4992,1),
('def_npc_gamma_prometheus_advanced_courier','def_kernel_thelodica',1820,7280,1),
('def_npc_gamma_prometheus_advanced_courier','def_kernel_hitech',910,3640,1),
('def_npc_gamma_prometheus_advanced_courier','def_kernel_common',780,3120,1),
('def_npc_gamma_prometheus_advanced_courier','def_material_boss_gamma_thelodica',40,60,1),
('def_npc_gamma_prometheus_advanced_courier','def_ammo_small_lasercrystal_rewb',80,120,0.5),
('def_npc_gamma_prometheus_advanced_courier','def_ammo_medium_lasercrystal_rewa',80,120,0.5),
('def_npc_gamma_prometheus_advanced_courier','def_named3_medium_laser',1,1,0.22),
('def_npc_gamma_prometheus_advanced_courier','def_named3_small_laser',1,1,0.22),
('def_npc_gamma_prometheus_advanced_courier','def_named3_small_core_booster',1,1,0.22),
('def_npc_gamma_prometheus_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_prometheus_advanced_courier','def_named3_webber',1,1,0.22),
('def_npc_gamma_prometheus_advanced_courier','def_reactore_core_runner',1,1,0.75),
('def_npc_gamma_prometheus_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_prometheus_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_intakt_advanced_courier','def_thelodica_reactor_plasma',2340,9360,1),
('def_npc_gamma_intakt_advanced_courier','def_kernel_thelodica',3549,14196,1),
('def_npc_gamma_intakt_advanced_courier','def_kernel_hitech',1300,5200,1),
('def_npc_gamma_intakt_advanced_courier','def_kernel_common',1521,6084,1),
('def_npc_gamma_intakt_advanced_courier','def_material_boss_gamma_thelodica',60,100,1),
('def_npc_gamma_intakt_advanced_courier','def_ammo_small_lasercrystal_rewa',60,120,0.5),
('def_npc_gamma_intakt_advanced_courier','def_named3_small_laser',1,1,0.22),
('def_npc_gamma_intakt_advanced_courier','def_named3_small_core_booster',1,1,0.22),
('def_npc_gamma_intakt_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_intakt_advanced_courier','def_named3_sensor_dampener',1,1,0.22),
('def_npc_gamma_intakt_advanced_courier','def_named3_small_shield_generator',1,1,0.22),
('def_npc_gamma_intakt_advanced_courier','def_reactore_core_runner',1,1,0.9),
('def_npc_gamma_intakt_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_intakt_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_waspish_advanced_courier','def_pelistal_reactor_plasma',2340,9360,1),
('def_npc_gamma_waspish_advanced_courier','def_kernel_pelistal',3549,14196,1),
('def_npc_gamma_waspish_advanced_courier','def_kernel_hitech',1300,5200,1),
('def_npc_gamma_waspish_advanced_courier','def_kernel_common',1521,6084,1),
('def_npc_gamma_waspish_advanced_courier','def_material_boss_gamma_pelistal',100,140,1),
('def_npc_gamma_waspish_advanced_courier','def_ammo_rocket_rewb',80,100,0.5),
('def_npc_gamma_waspish_advanced_courier','def_ammo_missile_rewa',40,60,0.5),
('def_npc_gamma_waspish_advanced_courier','def_named3_rocket_launcher',1,1,0.33),
('def_npc_gamma_waspish_advanced_courier','def_named3_missile_launcher',1,1,0.22),
('def_npc_gamma_waspish_advanced_courier','def_named3_medium_core_battery',1,1,0.22),
('def_npc_gamma_waspish_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_waspish_advanced_courier','def_named3_shield_hardener',1,1,0.22),
('def_npc_gamma_waspish_advanced_courier','def_reactore_core_assault',1,1,0.75),
('def_npc_gamma_waspish_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_waspish_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_castel_advanced_courier','def_pelistal_reactor_plasma',1248,4992,1),
('def_npc_gamma_castel_advanced_courier','def_kernel_pelistal',1820,7280,1),
('def_npc_gamma_castel_advanced_courier','def_kernel_hitech',910,3640,1),
('def_npc_gamma_castel_advanced_courier','def_kernel_common',780,3120,1),
('def_npc_gamma_castel_advanced_courier','def_material_boss_gamma_pelistal',40,60,1),
('def_npc_gamma_castel_advanced_courier','def_ammo_rocket_rewb',40,60,0.5),
('def_npc_gamma_castel_advanced_courier','def_ammo_missile_rewa',40,60,0.5),
('def_npc_gamma_castel_advanced_courier','def_named3_rocket_launcher',1,1,0.22),
('def_npc_gamma_castel_advanced_courier','def_named3_missile_launcher',1,1,0.22),
('def_npc_gamma_castel_advanced_courier','def_named3_small_shield_generator',1,1,0.22),
('def_npc_gamma_castel_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_castel_advanced_courier','def_named3_sensor_booster',1,1,0.22),
('def_npc_gamma_castel_advanced_courier','def_reactore_core_runner',1,1,0.75),
('def_npc_gamma_castel_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_castel_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_troiar_advanced_courier','def_pelistal_reactor_plasma',2340,9360,1),
('def_npc_gamma_troiar_advanced_courier','def_kernel_pelistal',3549,14196,1),
('def_npc_gamma_troiar_advanced_courier','def_kernel_hitech',1300,5200,1),
('def_npc_gamma_troiar_advanced_courier','def_kernel_common',1521,6084,1),
('def_npc_gamma_troiar_advanced_courier','def_material_boss_gamma_pelistal',60,100,1),
('def_npc_gamma_troiar_advanced_courier','def_ammo_missile_rewa',40,60,0.5),
('def_npc_gamma_troiar_advanced_courier','def_named3_missile_launcher',1,1,0.22),
('def_npc_gamma_troiar_advanced_courier','def_named3_small_core_booster',1,1,0.22),
('def_npc_gamma_troiar_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_troiar_advanced_courier','def_named3_small_energy_neutralizer',1,1,0.22),
('def_npc_gamma_troiar_advanced_courier','def_named3_small_energy_vampire',1,1,0.22),
('def_npc_gamma_troiar_advanced_courier','def_reactore_core_runner',1,1,0.9),
('def_npc_gamma_troiar_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_troiar_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_arbalest_advanced_courier','def_nuimqol_reactor_plasma',2340,9360,1),
('def_npc_gamma_arbalest_advanced_courier','def_kernel_nuimqol',3549,14196,1),
('def_npc_gamma_arbalest_advanced_courier','def_kernel_hitech',1300,5200,1),
('def_npc_gamma_arbalest_advanced_courier','def_kernel_common',1521,6084,1),
('def_npc_gamma_arbalest_advanced_courier','def_material_boss_gamma_nuimqol',100,140,1),
('def_npc_gamma_arbalest_advanced_courier','def_ammo_small_railgun_rewb',120,150,0.5),
('def_npc_gamma_arbalest_advanced_courier','def_ammo_medium_railgun_rewa',80,100,0.5),
('def_npc_gamma_arbalest_advanced_courier','def_named3_small_railgun',1,1,0.33),
('def_npc_gamma_arbalest_advanced_courier','def_named3_medium_railgun',1,1,0.22),
('def_npc_gamma_arbalest_advanced_courier','def_named3_small_core_booster',1,1,0.22),
('def_npc_gamma_arbalest_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_arbalest_advanced_courier','def_named3_small_armor_repairer',1,1,0.22),
('def_npc_gamma_arbalest_advanced_courier','def_reactore_core_assault',1,1,0.75),
('def_npc_gamma_arbalest_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_arbalest_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_yagel_advanced_courier','def_nuimqol_reactor_plasma',1248,4992,1),
('def_npc_gamma_yagel_advanced_courier','def_kernel_nuimqol',1820,7280,1),
('def_npc_gamma_yagel_advanced_courier','def_kernel_hitech',910,3640,1),
('def_npc_gamma_yagel_advanced_courier','def_kernel_common',780,3120,1),
('def_npc_gamma_yagel_advanced_courier','def_material_boss_gamma_nuimqol',40,60,1),
('def_npc_gamma_yagel_advanced_courier','def_ammo_small_railgun_rewb',80,100,0.5),
('def_npc_gamma_yagel_advanced_courier','def_ammo_medium_railgun_rewa',80,100,0.5),
('def_npc_gamma_yagel_advanced_courier','def_named3_small_railgun',1,1,0.22),
('def_npc_gamma_yagel_advanced_courier','def_named3_medium_railgun',1,1,0.22),
('def_npc_gamma_yagel_advanced_courier','def_named3_armor_repairer_upgrade',1,1,0.22),
('def_npc_gamma_yagel_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_yagel_advanced_courier','def_named3_sensor_booster',1,1,0.22),
('def_npc_gamma_yagel_advanced_courier','def_reactore_core_runner',1,1,0.75),
('def_npc_gamma_yagel_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_yagel_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_cameleon_advanced_courier','def_nuimqol_reactor_plasma',2340,9360,1),
('def_npc_gamma_cameleon_advanced_courier','def_kernel_nuimqol',3549,14196,1),
('def_npc_gamma_cameleon_advanced_courier','def_kernel_hitech',1300,5200,1),
('def_npc_gamma_cameleon_advanced_courier','def_kernel_common',1521,6084,1),
('def_npc_gamma_cameleon_advanced_courier','def_material_boss_gamma_nuimqol',60,100,1),
('def_npc_gamma_cameleon_advanced_courier','def_ammo_small_railgun_rewa',80,100,0.5),
('def_npc_gamma_cameleon_advanced_courier','def_named3_small_railgun',1,1,0.22),
('def_npc_gamma_cameleon_advanced_courier','def_named3_small_core_booster',1,1,0.22),
('def_npc_gamma_cameleon_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_cameleon_advanced_courier','def_named3_sensor_jammer',1,1,0.22),
('def_npc_gamma_cameleon_advanced_courier','def_named3_medium_energy_vampire',1,1,0.22),
('def_npc_gamma_cameleon_advanced_courier','def_reactore_core_runner',1,1,0.9),
('def_npc_gamma_cameleon_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_cameleon_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_locust_advanced_courier','def_common_reactor_plasma',2808,11232,1),
('def_npc_gamma_locust_advanced_courier','def_kernel_common',4563,18252,1),
('def_npc_gamma_locust_advanced_courier','def_kernel_hitech',2600,10400,1),
('def_npc_gamma_locust_advanced_courier','def_material_boss_gamma_syndicate',100,140,1),
('def_npc_gamma_locust_advanced_courier','def_ammo_small_projectile_rewb',200,250,0.5),
('def_npc_gamma_locust_advanced_courier','def_ammo_medium_projectile_rewa',120,160,0.5),
('def_npc_gamma_locust_advanced_courier','def_named3_medium_autocannon',1,1,0.22),
('def_npc_gamma_locust_advanced_courier','def_named3_small_autocannon',1,1,0.33),
('def_npc_gamma_locust_advanced_courier','def_named3_medium_armor_plate',1,1,0.22),
('def_npc_gamma_locust_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_locust_advanced_courier','def_named3_damage_mod_projectile',1,1,0.22),
('def_npc_gamma_locust_advanced_courier','def_reactore_core_assault',1,1,0.75),
('def_npc_gamma_locust_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_locust_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_vektor_advanced_courier','def_common_reactor_plasma',1500,6000,1),
('def_npc_gamma_vektor_advanced_courier','def_kernel_common',2340,9360,1),
('def_npc_gamma_vektor_advanced_courier','def_kernel_hitech',1820,7280,1),
('def_npc_gamma_vektor_advanced_courier','def_material_boss_gamma_syndicate',40,60,1),
('def_npc_gamma_vektor_advanced_courier','def_ammo_small_projectile_rewb',120,160,0.5),
('def_npc_gamma_vektor_advanced_courier','def_ammo_medium_projectile_rewa',120,160,0.5),
('def_npc_gamma_vektor_advanced_courier','def_named3_medium_autocannon',1,1,0.22),
('def_npc_gamma_vektor_advanced_courier','def_named3_small_autocannon',1,1,0.22),
('def_npc_gamma_vektor_advanced_courier','def_named3_small_armor_repairer',1,1,0.22),
('def_npc_gamma_vektor_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_vektor_advanced_courier','def_named3_sensor_jammer',1,1,0.22),
('def_npc_gamma_vektor_advanced_courier','def_reactore_core_runner',1,1,0.75),
('def_npc_gamma_vektor_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_vektor_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_helix_advanced_courier','def_common_reactor_plasma',2808,11232,1),
('def_npc_gamma_helix_advanced_courier','def_kernel_common',4563,18252,1),
('def_npc_gamma_helix_advanced_courier','def_kernel_hitech',2600,10400,1),
('def_npc_gamma_helix_advanced_courier','def_material_boss_gamma_syndicate',60,100,1),
('def_npc_gamma_helix_advanced_courier','def_ammo_small_projectile_rewa',120,160,0.5),
('def_npc_gamma_helix_advanced_courier','def_named3_small_autocannon',1,1,0.22),
('def_npc_gamma_helix_advanced_courier','def_named3_maneuvering_upgrade',1,1,0.22),
('def_npc_gamma_helix_advanced_courier','def_named3_mass_reductor',1,1,0.22),
('def_npc_gamma_helix_advanced_courier','def_named3_small_energy_vampire',1,1,0.22),
('def_npc_gamma_helix_advanced_courier','def_named3_webber',1,1,0.22),
('def_npc_gamma_helix_advanced_courier','def_reactore_core_runner',1,1,0.9),
('def_npc_gamma_helix_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_helix_advanced_courier','def_research_kit_9',1,1,0.15),


('def_npc_gamma_hermes_advanced_courier','def_common_reactor_plasma',1250,5000,1),
('def_npc_gamma_hermes_advanced_courier','def_kernel_hitech',3750,15000,1),
('def_npc_gamma_hermes_advanced_courier','def_material_boss_gamma_syndicate',240,300,1),
('def_npc_gamma_hermes_advanced_courier','def_ammo_small_projectile_rewa',150,300,1),
('def_npc_gamma_hermes_advanced_courier','def_ammo_medium_projectile_rewa',150,300,1),
('def_npc_gamma_hermes_advanced_courier','def_named3_webber',1,1,0.22),
('def_npc_gamma_hermes_advanced_courier','def_named3_small_autocannon',1,1,0.22),
('def_npc_gamma_hermes_advanced_courier','def_named3_medium_autocannon',1,1,0.22),
('def_npc_gamma_hermes_advanced_courier','def_robotshard_common_basic',150,500,0.5),
('def_npc_gamma_hermes_advanced_courier','def_robotshard_common_advanced',150,300,0.5),
('def_npc_gamma_hermes_advanced_courier','def_robotshard_common_expert',150,200,0.5),
('def_npc_gamma_hermes_advanced_courier','def_npc_egg_nuimqol_medium_miniboss3_capsule',1,1,0.2),
('def_npc_gamma_hermes_advanced_courier','def_npc_egg_pelistal_medium_miniboss3_capsule',1,1,0.2),
('def_npc_gamma_hermes_advanced_courier','def_npc_egg_thelodica_medium_miniboss3_capsule',1,1,0.2),
('def_npc_gamma_hermes_advanced_courier','def_mobile_teleport_capsule_standard',1,1,0.5),
('def_npc_gamma_hermes_advanced_courier','def_research_kit_8',1,2,0.9),
('def_npc_gamma_hermes_advanced_courier','def_research_kit_9',1,1,0.75),
('def_npc_gamma_hermes_advanced_courier','def_research_kit_10',1,1,0.5),


('def_npc_gamma_sequer_advanced_courier','def_common_reactor_plasma',1875,7500,1),
('def_npc_gamma_sequer_advanced_courier','def_kernel_hitech',2500,10000,1),
('def_npc_gamma_sequer_advanced_courier','def_material_boss_gamma_syndicate',140,180,1),
('def_npc_gamma_sequer_advanced_courier','def_named3_medium_core_battery',1,1,0.22),
('def_npc_gamma_sequer_advanced_courier','def_named3_shield_hardener',1,1,0.22),
('def_npc_gamma_sequer_advanced_courier','def_npc_egg_nuimqol_medium_expert_capsule',1,1,0.22),
('def_npc_gamma_sequer_advanced_courier','def_npc_egg_pelistal_medium_expert_capsule',1,1,0.22),
('def_npc_gamma_sequer_advanced_courier','def_npc_egg_thelodica_medium_expert_capsule',1,1,0.22),
('def_npc_gamma_sequer_advanced_courier','def_robotshard_common_basic',100,500,0.5),
('def_npc_gamma_sequer_advanced_courier','def_robotshard_common_advanced',100,300,0.5),
('def_npc_gamma_sequer_advanced_courier','def_robotshard_common_expert',100,200,0.5),
('def_npc_gamma_sequer_advanced_courier','def_research_kit_8',1,2,0.75),
('def_npc_gamma_sequer_advanced_courier','def_research_kit_9',1,1,0.5),
('def_npc_gamma_sequer_advanced_courier','def_research_kit_10',1,1,0.25),


('def_npc_gamma_ikarus_advanced_courier','def_common_reactor_plasma',625,2500,1),
('def_npc_gamma_ikarus_advanced_courier','def_kernel_hitech',750,3000,1),
('def_npc_gamma_ikarus_advanced_courier','def_material_boss_gamma_syndicate',80,120,1),
('def_npc_gamma_ikarus_advanced_courier','def_named3_medium_energy_vampire',1,1,0.22),
('def_npc_gamma_ikarus_advanced_courier','def_npc_egg_nuimqol_small_expert_capsule',1,1,0.22),
('def_npc_gamma_ikarus_advanced_courier','def_npc_egg_pelistal_small_expert_capsule',1,1,0.22),
('def_npc_gamma_ikarus_advanced_courier','def_npc_egg_thelodica_small_expert_capsule',1,1,0.22),
('def_npc_gamma_ikarus_advanced_courier','def_robotshard_common_basic',50,250,0.5),
('def_npc_gamma_ikarus_advanced_courier','def_robotshard_common_advanced',50,150,0.5),
('def_npc_gamma_ikarus_advanced_courier','def_robotshard_common_expert',50,100,0.5),
('def_npc_gamma_ikarus_advanced_courier','def_research_kit_8',1,2,0.25),
('def_npc_gamma_ikarus_advanced_courier','def_research_kit_9',1,1,0.15),
('def_npc_gamma_ikarus_advanced_courier','def_research_kit_10',1,1,0.1);


PRINT N'DELETE/RE-INSERT LOOTS FOR SPECIAL GAMMA NPC TYPES';
SELECT * FROM npcloot WHERE definition IN (
	SELECT definition FROM entitydefaults where definitionname IN (
		SELECT DISTINCT defName FROM #LOOTS
	)
);

DELETE FROM npcloot WHERE definition IN (
	SELECT definition FROM entitydefaults where definitionname IN (
		SELECT DISTINCT defName FROM #LOOTS
	)
);

INSERT INTO npcloot (definition, lootdefinition, minquantity, quantity, probability, repackaged, dontdamage)
SELECT 
	(SELECT TOP 1 definition FROM entitydefaults WHERE definitionname=defName),
	(SELECT TOP 1 definition FROM entitydefaults WHERE definitionname=lootName),
	minQuant, maxQuant, prob, 0, CASE WHEN lootName like '%named%' or lootName like '%standard%' THEN 0 ELSE 1 END
 FROM #LOOTS;

 DROP TABLE IF EXISTS #LOOTS;
 GO