USE [perpetuumsa]
GO

-------------------------------------------------
-- PBS Research tree costs
--
--
-- Date modified: 2021/10/13
-------------------------------------------------

DROP TABLE IF EXISTS #KERNELCOSTS;
CREATE TABLE #KERNELCOSTS(
	defName VARCHAR(128),
	kernelType VARCHAR(128),
	cost INT
);
INSERT INTO #KERNELCOSTS (defName, kernelType, cost) VALUES
('def_construction_module_ammo_t1','hitech',5000),
('def_construction_module_ammo_t1','industrial',5000),
('def_construction_module_ammo_t2','hitech',10000),
('def_construction_module_ammo_t2','industrial',10000),
('def_construction_module_ammo_t3','hitech',20000),
('def_construction_module_ammo_t3','industrial',20000),
('def_reactor_booster_a','hitech',10000),
('def_reactor_booster_b','hitech',25000),
('def_reactor_booster_c','hitech',75000),
('def_pbs_docking_base_small_capsule','common',25000),
('def_pbs_docking_base_small_capsule','hitech',50000),
('def_pbs_docking_base_medium_capsule','common',125000),
('def_pbs_docking_base_medium_capsule','hitech',250000),
('def_pbs_docking_base_large_capsule','common',375000),
('def_pbs_docking_base_large_capsule','hitech',750000),
('def_pbs_reactor_small_capsule','common',12500),
('def_pbs_reactor_small_capsule','hitech',25000),
('def_pbs_reactor_medium_capsule','common',50000),
('def_pbs_reactor_medium_capsule','hitech',75000),
('def_pbs_reactor_large_capsule','common',100000),
('def_pbs_reactor_large_capsule','hitech',175000),
('def_pbs_core_transmitter_small_capsule','common',10000),
('def_pbs_core_transmitter_small_capsule','hitech',20000),
('def_pbs_core_transmitter_medium_capsule','common',25000),
('def_pbs_core_transmitter_medium_capsule','hitech',50000),
('def_pbs_core_transmitter_large_capsule','common',50000),
('def_pbs_core_transmitter_large_capsule','hitech',100000),
('def_pbs_XL_core_transmitter_small_capsule','common',12500),
('def_pbs_XL_core_transmitter_small_capsule','hitech',25000),
('def_pbs_XL_core_transmitter_medium_capsule','common',31300),
('def_pbs_XL_core_transmitter_medium_capsule','hitech',62500),
('def_pbs_XL_core_transmitter_large_capsule','common',62500),
('def_pbs_XL_core_transmitter_large_capsule','hitech',125000),
('def_pbs_core_battery_small_capsule','common',15000),
('def_pbs_core_battery_small_capsule','hitech',30000),
('def_pbs_core_battery_medium_capsule','common',37500),
('def_pbs_core_battery_medium_capsule','hitech',75000),
('def_pbs_core_battery_large_capsule','common',75000),
('def_pbs_core_battery_large_capsule','hitech',150000),
('def_pbs_production_upgrade_small_capsule','industrial',23000),
('def_pbs_production_upgrade_small_capsule','common',12000),
('def_pbs_production_upgrade_medium_capsule','hitech',46000),
('def_pbs_production_upgrade_medium_capsule','industrial',28000),
('def_pbs_production_upgrade_medium_capsule','common',14000),
('def_pbs_production_upgrade_large_capsule','hitech',105000),
('def_pbs_production_upgrade_large_capsule','industrial',53000),
('def_pbs_production_upgrade_large_capsule','common',32000),
('def_pbs_mining_tower_small_capsule','common',25000),
('def_pbs_mining_tower_small_capsule','industrial',50000),
('def_pbs_mining_tower_medium_capsule','common',50000),
('def_pbs_mining_tower_medium_capsule','hitech',75000),
('def_pbs_mining_tower_medium_capsule','industrial',125000),
('def_pbs_mining_tower_large_capsule','common',125000),
('def_pbs_mining_tower_large_capsule','hitech',250000),
('def_pbs_mining_tower_large_capsule','industrial',375000),
('def_pbs_refinery_small_capsule','industrial',15000),
('def_pbs_refinery_small_capsule','common',7500),
('def_pbs_refinery_medium_capsule','hitech',25000),
('def_pbs_refinery_medium_capsule','industrial',15000),
('def_pbs_refinery_medium_capsule','common',7500),
('def_pbs_refinery_large_capsule','hitech',50000),
('def_pbs_refinery_large_capsule','industrial',25000),
('def_pbs_refinery_large_capsule','common',15000),
('def_pbs_repair_small_capsule','common',15000),
('def_pbs_repair_small_capsule','industrial',7500),
('def_pbs_repair_medium_capsule','hitech',25000),
('def_pbs_repair_medium_capsule','industrial',15000),
('def_pbs_repair_medium_capsule','common',7500),
('def_pbs_repair_large_capsule','hitech',50000),
('def_pbs_repair_large_capsule','industrial',25000),
('def_pbs_repair_large_capsule','common',15000),
('def_pbs_reprocessor_small_capsule','common',18000),
('def_pbs_reprocessor_small_capsule','industrial',9000),
('def_pbs_reprocessor_medium_capsule','hitech',33000),
('def_pbs_reprocessor_medium_capsule','industrial',20000),
('def_pbs_reprocessor_medium_capsule','common',10000),
('def_pbs_reprocessor_large_capsule','hitech',70000),
('def_pbs_reprocessor_large_capsule','industrial',35000),
('def_pbs_reprocessor_large_capsule','common',21000),
('def_pbs_mill_small_capsule','common',18000),
('def_pbs_mill_small_capsule','industrial',9000),
('def_pbs_mill_medium_capsule','hitech',33000),
('def_pbs_mill_medium_capsule','industrial',20000),
('def_pbs_mill_medium_capsule','common',10000),
('def_pbs_mill_large_capsule','hitech',70000),
('def_pbs_mill_large_capsule','industrial',35000),
('def_pbs_mill_large_capsule','common',21000),
('def_pbs_prototyper_small_capsule','common',23000),
('def_pbs_prototyper_small_capsule','industrial',12000),
('def_pbs_prototyper_medium_capsule','hitech',46000),
('def_pbs_prototyper_medium_capsule','industrial',28000),
('def_pbs_prototyper_medium_capsule','common',14000),
('def_pbs_prototyper_large_capsule','hitech',105000),
('def_pbs_prototyper_large_capsule','industrial',53000),
('def_pbs_prototyper_large_capsule','common',32000),
('def_pbs_research_lab_small_capsule','industrial',32000),
('def_pbs_research_lab_small_capsule','common',17000),
('def_pbs_research_lab_medium_capsule','hitech',69000),
('def_pbs_research_lab_medium_capsule','industrial',42000),
('def_pbs_research_lab_medium_capsule','common',21000),
('def_pbs_research_lab_large_capsule','hitech',168000),
('def_pbs_research_lab_large_capsule','industrial',85000),
('def_pbs_research_lab_large_capsule','common',51000),
('def_pbs_calibration_forge_small_capsule','common',48000),
('def_pbs_calibration_forge_small_capsule','industrial',26000),
('def_pbs_calibration_forge_medium_capsule','hitech',110000),
('def_pbs_calibration_forge_medium_capsule','industrial',67000),
('def_pbs_calibration_forge_medium_capsule','common',34000),
('def_pbs_calibration_forge_large_capsule','hitech',286000),
('def_pbs_calibration_forge_large_capsule','industrial',145000),
('def_pbs_calibration_forge_large_capsule','common',87000),
('def_pbs_research_kit_forge_small_capsule','common',48000),
('def_pbs_research_kit_forge_small_capsule','industrial',26000),
('def_pbs_research_kit_forge_medium_capsule','hitech',110000),
('def_pbs_research_kit_forge_medium_capsule','industrial',67000),
('def_pbs_research_kit_forge_medium_capsule','common',34000),
('def_pbs_research_kit_forge_large_capsule','hitech',286000),
('def_pbs_research_kit_forge_large_capsule','industrial',145000),
('def_pbs_research_kit_forge_large_capsule','common',87000),
('def_pbs_control_tower_small_capsule','nuimqol',10000),
('def_pbs_control_tower_small_capsule','thelodica',10000),
('def_pbs_control_tower_small_capsule','pelistal',10000),
('def_pbs_control_tower_medium_capsule','nuimqol',25000),
('def_pbs_control_tower_medium_capsule','thelodica',25000),
('def_pbs_control_tower_medium_capsule','pelistal',25000),
('def_pbs_control_tower_medium_capsule','hitech',50000),
('def_pbs_control_tower_large_capsule','nuimqol',50000),
('def_pbs_control_tower_large_capsule','thelodica',50000),
('def_pbs_control_tower_large_capsule','pelistal',50000),
('def_pbs_control_tower_large_capsule','hitech',200000),
('def_pbs_armor_repairer_small_capsule','common',12500),
('def_pbs_armor_repairer_small_capsule','hitech',25000),
('def_pbs_armor_repairer_medium_capsule','common',50000),
('def_pbs_armor_repairer_medium_capsule','hitech',125000),
('def_pbs_armor_repairer_large_capsule','common',75000),
('def_pbs_armor_repairer_large_capsule','hitech',250000),
('def_pbs_turret_rail_small_capsule','common',25000),
('def_pbs_turret_rail_small_capsule','nuimqol',50000),
('def_pbs_turret_rail_medium_capsule','common',50000),
('def_pbs_turret_rail_medium_capsule','hitech',75000),
('def_pbs_turret_rail_medium_capsule','nuimqol',125000),
('def_pbs_turret_rail_large_capsule','common',125000),
('def_pbs_turret_rail_large_capsule','hitech',250000),
('def_pbs_turret_rail_large_capsule','nuimqol',375000),
('def_pbs_turret_laser_small_capsule','common',25000),
('def_pbs_turret_laser_small_capsule','thelodica',50000),
('def_pbs_turret_laser_medium_capsule','common',50000),
('def_pbs_turret_laser_medium_capsule','hitech',75000),
('def_pbs_turret_laser_medium_capsule','thelodica',125000),
('def_pbs_turret_laser_large_capsule','common',125000),
('def_pbs_turret_laser_large_capsule','hitech',250000),
('def_pbs_turret_laser_large_capsule','thelodica',375000),
('def_pbs_turret_missile_small_capsule','common',25000),
('def_pbs_turret_missile_small_capsule','pelistal',50000),
('def_pbs_turret_missile_medium_capsule','common',50000),
('def_pbs_turret_missile_medium_capsule','hitech',75000),
('def_pbs_turret_missile_medium_capsule','pelistal',125000),
('def_pbs_turret_missile_large_capsule','common',125000),
('def_pbs_turret_missile_large_capsule','hitech',250000),
('def_pbs_turret_missile_large_capsule','pelistal',375000),
('def_pbs_effect_supplier_small_capsule','nuimqol',10000),
('def_pbs_effect_supplier_small_capsule','thelodica',10000),
('def_pbs_effect_supplier_small_capsule','pelistal',10000),
('def_pbs_effect_supplier_medium_capsule','nuimqol',25000),
('def_pbs_effect_supplier_medium_capsule','thelodica',25000),
('def_pbs_effect_supplier_medium_capsule','pelistal',25000),
('def_pbs_effect_supplier_medium_capsule','hitech',50000),
('def_pbs_effect_supplier_large_capsule','nuimqol',50000),
('def_pbs_effect_supplier_large_capsule','thelodica',50000),
('def_pbs_effect_supplier_large_capsule','pelistal',50000),
('def_pbs_effect_supplier_large_capsule','hitech',200000),
('def_pbs_turret_ew_small_capsule','common',25000),
('def_pbs_turret_ew_small_capsule','hitech',50000),
('def_pbs_turret_ew_medium_capsule','common',75000),
('def_pbs_turret_ew_medium_capsule','hitech',175000),
('def_pbs_turret_ew_large_capsule','common',250000),
('def_pbs_turret_ew_large_capsule','hitech',375000),
('def_pbs_maskertower_small_capsule','common',15000),
('def_pbs_maskertower_small_capsule','hitech',35000),
('def_pbs_maskertower_medium_capsule','common',35000),
('def_pbs_maskertower_medium_capsule','hitech',75000),
('def_pbs_maskertower_large_capsule','common',75000),
('def_pbs_maskertower_large_capsule','hitech',125000),
('def_pbs_aura_emitter_small_capsule','common',19500),
('def_pbs_aura_emitter_small_capsule','hitech',45500),
('def_pbs_aura_emitter_medium_capsule','common',45500),
('def_pbs_aura_emitter_medium_capsule','hitech',97500),
('def_pbs_aura_emitter_large_capsule','common',97500),
('def_pbs_aura_emitter_large_capsule','hitech',162500),
('def_pbs_energywell_small_capsule','common',10000),
('def_pbs_energywell_small_capsule','hitech',20000),
('def_pbs_energywell_medium_capsule','common',20000),
('def_pbs_energywell_medium_capsule','hitech',50000),
('def_pbs_energywell_large_capsule','common',50000),
('def_pbs_energywell_large_capsule','hitech',100000),
('def_pbs_highwaynode_small_capsule','common',25000),
('def_pbs_highwaynode_small_capsule','hitech',50000),
('def_pbs_highwaynode_medium_capsule','common',50000),
('def_pbs_highwaynode_medium_capsule','hitech',75000),
('def_pbs_highwaynode_large_capsule','common',75000),
('def_pbs_highwaynode_large_capsule','hitech',150000);

PRINT N'SELECT CURRENT VALUES';
SELECT * FROM techtreenodeprices WHERE definition IN (
	SELECT definition FROM entitydefaults WHERE definitionname IN (
		SELECT DISTINCT defName FROM #KERNELCOSTS
	)
);

PRINT N'DELETE/REINSERT node prices';
DELETE FROM techtreenodeprices WHERE definition IN (
	SELECT definition FROM entitydefaults WHERE definitionname IN (
		SELECT DISTINCT defName FROM #KERNELCOSTS
	)
);

PRINT N'UPDATE/INSERT ALL NODE COSTS';
MERGE techtreenodeprices p USING #KERNELCOSTS k
ON p.definition = (SELECT TOP 1 definition FROM entitydefaults WHERE definitionname=k.defName) AND
p.pointtype = (SELECT TOP 1 id FROM techtreepointtypes WHERE name=k.kernelType)
WHEN MATCHED
    THEN UPDATE SET
		amount = k.cost
WHEN NOT MATCHED
    THEN INSERT (definition, pointtype, amount) VALUES
		((SELECT TOP 1 definition FROM entitydefaults WHERE definitionname=k.defName),
		(SELECT TOP 1 id FROM techtreepointtypes WHERE name=k.kernelType),
		k.cost);



DROP TABLE IF EXISTS #KERNELCOSTS;
GO
